import { readFileSync, writeFileSync } from "node:fs";

function readExampleField(name) {
  const raw = readFileSync(new URL("../js/config.example.js", import.meta.url), "utf8");
  const match = raw.match(new RegExp(`${name}:\\s*"([^"]*)"`));
  return match ? match[1] : "";
}

const supabaseUrl =
  process.env.SUPABASE_URL ||
  readExampleField("supabaseUrl") ||
  "https://edwvrriuwzaaqznklrgi.supabase.co";
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || readExampleField("supabaseAnonKey") || "";

if (!supabaseAnonKey || supabaseAnonKey.includes("你的")) {
  console.error(
    "Missing SUPABASE_ANON_KEY. Set env var, Cloudflare build env, or fill admin/js/config.example.js for local defaults."
  );
  process.exit(1);
}

const config = `// Generated by admin/scripts/build-config.mjs — do not commit
window.CHINAGO_ADMIN_CONFIG = ${JSON.stringify({ supabaseUrl, supabaseAnonKey }, null, 2)};
`;

writeFileSync(new URL("../js/config.js", import.meta.url), config);
console.log("Wrote admin/js/config.js");
