import { readFileSync, writeFileSync } from "node:fs";

function readJsExampleField(fileUrl, fieldName) {
  try {
    const raw = readFileSync(fileUrl, "utf8");
    const match = raw.match(new RegExp(`${fieldName}:\\s*"([^"]*)"`));
    return match ? match[1] : "";
  } catch {
    return "";
  }
}

const adminExample = new URL("../js/config.example.js", import.meta.url);
const webExample = new URL("../../web/config.example.js", import.meta.url);

const supabaseUrl =
  process.env.SUPABASE_URL ||
  readJsExampleField(adminExample, "supabaseUrl") ||
  readJsExampleField(webExample, "supabaseUrl") ||
  "https://edwvrriuwzaaqznklrgi.supabase.co";

const supabaseAnonKey =
  process.env.SUPABASE_ANON_KEY ||
  readJsExampleField(adminExample, "supabaseAnonKey") ||
  readJsExampleField(webExample, "supabaseAnonKey") ||
  "";

const invalidKey =
  !supabaseAnonKey || supabaseAnonKey.includes("你的") || supabaseAnonKey.includes("anon_key");

if (invalidKey) {
  console.error(
    "Missing SUPABASE_ANON_KEY. Add GitHub Actions secret SUPABASE_ANON_KEY, Cloudflare build env, or set web/config.example.js / admin/js/config.example.js."
  );
  process.exit(1);
}

const config = `// Generated by admin/scripts/build-config.mjs — do not commit
window.CHINAGO_ADMIN_CONFIG = ${JSON.stringify({ supabaseUrl, supabaseAnonKey }, null, 2)};
`;

writeFileSync(new URL("../js/config.js", import.meta.url), config);
console.log("Wrote admin/js/config.js");
