/* ChinaGo Admin — table schema definitions */

(function () {
  const App = window.ChinaGoAdmin;

  const CATEGORY_OPTIONS = ["palace", "temple", "park", "museum", "wall", "garden", "sight", "market", "other"];
  const PRIORITY_OPTIONS = ["P0", "P1", "P2"];
  const CHECKLIST_PHASE_OPTIONS = [
    { value: "before_departure", label: "出发前" },
    { value: "on_arrival", label: "抵达后" },
    { value: "during_trip", label: "行程中" },
  ];
  const TIME_SLOT_OPTIONS = ["AM", "PM", "EVE"];

  App.TABLES = {
    app_settings: {
      label: "应用配置",
      single: true,
      pk: "id",
      order: null,
      fields: [
        { key: "id", type: "text", readonly: true, advanced: true },
        { key: "use_remote_content", type: "bool", label: "远程内容（Live Services）" },
        { key: "use_remote_ai", type: "bool", label: "远程 AI" },
        { key: "use_remote_iap", type: "bool", label: "远程内购" },
        { key: "support_email", type: "text", label: "反馈邮箱" },
        { key: "about_title", type: "text", label: "关于 · 标题" },
        { key: "about_version", type: "text", label: "关于 · 版本号" },
        { key: "about_body", type: "textarea", label: "关于 · 简介" },
        { key: "iap_pro_title", type: "text", label: "内购 · Pro 标题" },
        { key: "iap_pro_price", type: "text", label: "内购 · Pro 价格文案" },
        { key: "iap_pro_trial_text", type: "text", label: "内购 · 试用文案" },
        { key: "iap_pro_features", type: "features_list", label: "内购 · Pro 权益" },
        { key: "iap_single_price_label", type: "text", label: "内购 · 单购按钮文案" },
        { key: "assistant_greeting_general", type: "textarea", label: "助手 · 通用问候" },
        { key: "assistant_greeting_planning", type: "textarea", label: "助手 · 规划问候" },
        { key: "plan_alert_message", type: "textarea", label: "Plan · 顶部警告文案" },
        { key: "plan_alert_link_city_id", type: "ref_city", label: "Plan · 警告链接城市", allowEmpty: true },
        { key: "plan_alert_link_attraction_id", type: "ref_attraction", label: "Plan · 警告链接景点", allowEmpty: true, filterByCityField: "plan_alert_link_city_id" },
        { key: "plan_alert_link_label", type: "text", label: "Plan · 警告链接按钮文案" },
        { key: "free_audio_preview_seconds", type: "number", label: "音频 · 免费试听秒数" },
      ],
    },
    assistant_chips: {
      label: "助手快捷芯片",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "label", label: "标签" },
        { key: "scenario_id", label: "场景", ref: "scenario" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "label", slugPrefix: "chip", required: true },
        { key: "scenario_id", type: "ref_scenario", required: true, label: "助手场景" },
        { key: "label", type: "text", required: true, label: "显示文字" },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    cities: {
      label: "城市",
      pk: "id",
      order: "display_order",
      listColumns: [
        { key: "name", label: "英文名" },
        { key: "chinese_name", label: "中文名" },
        { key: "emoji", label: "表情" },
        { key: "is_published", label: "已发布" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "name", required: true },
        { key: "name", type: "text", required: true, label: "英文名" },
        { key: "chinese_name", type: "text", required: true, label: "中文名" },
        { key: "emoji", type: "text", label: "表情符号" },
        { key: "cover_image_path", type: "image_preview", label: "封面图" },
        { key: "_cover_upload", type: "image_upload", label: "上传封面", uploadFolder: "cities", uploadTarget: "cover_image_path" },
        { key: "description", type: "textarea", label: "简介" },
        { key: "best_for", type: "tags", label: "适合人群（逗号分隔）" },
        { key: "season_note", type: "text", label: "季节提示" },
        { key: "best_time_to_visit", type: "text", label: "最佳游览时间" },
        { key: "avg_days_recommended", type: "number", label: "推荐天数" },
        { key: "attraction_count", type: "number", label: "景点数量" },
        { key: "display_order", type: "number", label: "排序" },
        { key: "is_published", type: "bool", label: "已发布" },
      ],
    },
    attractions: {
      label: "景点",
      pk: "id",
      order: "display_order",
      listColumns: [
        { key: "name", label: "名称" },
        { key: "city_id", label: "城市", ref: "city" },
        { key: "priority", label: "优先级" },
        { key: "is_published", label: "已发布" },
      ],
      fields: [
        { key: "name", type: "text", required: true, label: "英文名" },
        { key: "chinese_name", type: "text", required: true, label: "中文名" },
        { key: "city_id", type: "ref_city", required: true, label: "所属城市" },
        { key: "category", type: "enum", options: CATEGORY_OPTIONS, label: "类型" },
        { key: "summary", type: "textarea", label: "摘要" },
        { key: "introduction", type: "richtext", label: "书面解说（长文）" },
        { key: "priority", type: "enum", options: PRIORITY_OPTIONS, label: "优先级" },
        { key: "ticket_price", type: "text", label: "门票" },
        { key: "recommended_duration", type: "text", label: "建议时长" },
        { key: "opening_hours", type: "text", label: "开放时间" },
        { key: "closed_days", type: "text", label: "闭馆日" },
        { key: "requires_advance_booking", type: "bool", label: "需提前预约" },
        { key: "metro_access", type: "text", label: "地铁" },
        { key: "western_visitor_tips", type: "string_list", label: "西方游客贴士" },
        { key: "nearby_places", type: "place_list", label: "周边推荐" },
        { key: "cover_image_path", type: "image_preview", label: "封面图" },
        { key: "_cover_upload", type: "image_upload", label: "上传封面", uploadFolder: "attractions", uploadTarget: "cover_image_path" },
        { key: "is_published", type: "bool", label: "已发布" },
        { key: "display_order", type: "number", label: "排序" },
        { key: "id", type: "slug", slugSource: "name", slugPrefixField: "city_id", required: true },
        { key: "audio_guide_count", type: "number", label: "音频导览数", advanced: true },
        { key: "iap_product_id", type: "text", label: "内购 Product ID", advanced: true },
      ],
    },
    checklist_items: {
      label: "行前清单",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "title_en", label: "标题" },
        { key: "city_id", label: "城市", ref: "city" },
        { key: "phase", label: "阶段" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "title_en", slugPrefix: "cl", required: true },
        { key: "city_id", type: "ref_city", label: "所属城市", allowEmpty: true, emptyLabel: "全局（所有城市）" },
        { key: "phase", type: "enum", options: CHECKLIST_PHASE_OPTIONS, required: true, label: "阶段" },
        { key: "group_title", type: "text", required: true, label: "分组标题" },
        { key: "title_en", type: "text", required: true, label: "英文标题" },
        { key: "estimated_minutes", type: "number", label: "预计分钟" },
        { key: "display_tags", type: "tags", label: "标签（逗号分隔）" },
        { key: "cultural_tip", type: "textarea", label: "文化提示" },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    home_tips: {
      label: "首页提示",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "headline", label: "标题" },
        { key: "city_id", label: "城市", ref: "city" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "headline", slugPrefix: "tip", required: true },
        { key: "city_id", type: "ref_city", label: "城市", allowEmpty: true },
        { key: "kicker", type: "text", label: "角标" },
        { key: "headline", type: "text", required: true, label: "主标题" },
        { key: "body", type: "textarea", required: true, label: "正文" },
        { key: "link_label", type: "text", label: "链接按钮文字" },
        { key: "link_attraction_id", type: "ref_attraction", label: "链接景点", allowEmpty: true, filterByCityField: "city_id" },
        { key: "link_url", type: "text", label: "外链 URL" },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    city_routes: {
      label: "城市路线",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "title", label: "标题" },
        { key: "city_id", label: "城市", ref: "city" },
        { key: "days", label: "天数" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "title", slugPrefixField: "city_id", required: true },
        { key: "city_id", type: "ref_city", required: true, label: "城市" },
        { key: "title", type: "text", required: true, label: "路线标题" },
        { key: "days", type: "number", required: true, label: "天数" },
        { key: "summary", type: "textarea", required: true, label: "简介" },
        { key: "sort_order", type: "number" },
      ],
    },
    audio_guides: {
      label: "音频导览",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "title_en", label: "标题" },
        { key: "attraction_id", label: "景点", ref: "attraction" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "title_en", type: "text", required: true, label: "标题" },
        { key: "attraction_id", type: "ref_attraction", required: true, label: "所属景点" },
        { key: "id", type: "slug", slugSource: "title_en", slugPrefix: "ag", required: true },
        { key: "description", type: "textarea", label: "说明" },
        { key: "duration_seconds", type: "number", label: "时长（秒）" },
        { key: "audio_url", type: "audio_preview", label: "音频地址" },
        { key: "_audio_upload", type: "audio_upload", label: "上传音频" },
        { key: "quote", type: "textarea", label: "开场引文" },
        { key: "segments", type: "segment_list", label: "章节时间轴" },
        { key: "is_main_guide", type: "bool", label: "主线路" },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    shopping_items: {
      label: "购物清单",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "title_en", label: "标题" },
        { key: "city_id", label: "城市", ref: "city" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "title_en", slugPrefix: "shop", required: true },
        { key: "city_id", type: "ref_city", label: "城市", allowEmpty: true, emptyLabel: "全局" },
        { key: "title_en", type: "text", required: true },
        { key: "note_en", type: "textarea" },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    reading_list: {
      label: "阅读清单",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "title", label: "书名" },
        { key: "author", label: "作者" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "title", slugPrefix: "read", required: true },
        { key: "city_ids", type: "ref_cities_multi", label: "关联城市" },
        { key: "title", type: "text", required: true },
        { key: "author", type: "text", required: true },
        { key: "genre", type: "text", required: true },
        { key: "synopsis_en", type: "textarea", required: true },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    hotels: {
      label: "酒店",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "name", label: "名称" },
        { key: "city_id", label: "城市", ref: "city" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "name", slugPrefix: "hotel", slugPrefixField: "city_id", required: true },
        { key: "city_id", type: "ref_city", required: true, label: "城市" },
        { key: "name", type: "text", required: true },
        { key: "chinese_name", type: "text", required: true },
        { key: "stars", type: "number", label: "星级" },
        { key: "price_min_usd", type: "number", label: "最低价 USD" },
        { key: "has_english_staff", type: "bool", label: "有英语服务" },
        { key: "english_staff_note", type: "textarea" },
        { key: "language_tip", type: "textarea" },
        { key: "location_note", type: "textarea" },
        { key: "booking_platforms", type: "tags", label: "预订平台" },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    passport_countries: {
      label: "护照国家",
      pk: "code",
      order: "display_order",
      listColumns: [
        { key: "code", label: "代码" },
        { key: "name", label: "名称" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "code", type: "text", required: true, label: "国家代码（如 GB）" },
        { key: "name", type: "text", required: true },
        { key: "flag", type: "text", label: "国旗 emoji" },
        { key: "display_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    visa_rules: {
      label: "签证规则",
      pk: "country_code",
      order: "country_code",
      listColumns: [
        { key: "country_code", label: "国家", ref: "country" },
        { key: "headline", label: "标题" },
        { key: "visa_free", label: "免签" },
      ],
      fields: [
        { key: "country_code", type: "ref_country", required: true, label: "国家" },
        { key: "country_name", type: "text", required: true, label: "国家名（自动建议）", autoFromCountry: true },
        { key: "flag", type: "text", label: "国旗" },
        { key: "visa_free", type: "bool", label: "免签" },
        { key: "stay_days", type: "number", label: "停留天数" },
        { key: "headline", type: "text", required: true },
        { key: "details", type: "visa_detail_list", label: "详情条目" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    culture_tips: {
      label: "文化贴士",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "title", label: "标题" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "title", slugPrefix: "culture", required: true },
        { key: "emoji", type: "text" },
        { key: "title", type: "text", required: true },
        { key: "preview", type: "textarea", required: true },
        { key: "body", type: "textarea", required: true },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    assistant_replies: {
      label: "助手回复",
      pk: "scenario_id",
      order: "scenario_id",
      listColumns: [
        { key: "scenario_id", label: "场景 ID" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "scenario_id", type: "text", required: true, label: "场景 ID（如 emergency）" },
        { key: "user_message", type: "textarea", label: "用户消息示例" },
        { key: "assistant_message", type: "textarea", required: true, label: "助手回复" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    emergency_config: {
      label: "紧急联系",
      single: true,
      pk: "id",
      order: null,
      fields: [
        { key: "id", type: "text", readonly: true, advanced: true },
        { key: "embassy_note", type: "textarea", required: true, label: "使馆说明" },
        { key: "contacts", type: "contact_list", label: "紧急电话" },
      ],
    },
    content_itineraries: {
      label: "行程模板",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "title", label: "标题" },
        { key: "kind", label: "类型" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "title", slugPrefix: "itin", required: true },
        { key: "kind", type: "enum", options: [
          { value: "sample", label: "示例行程 (sample)" },
          { value: "planning", label: "规划草案 (planning)" },
        ], required: true, label: "类型" },
        { key: "title", type: "text", required: true },
        { key: "meta", type: "text", required: true, label: "元信息" },
        { key: "route_summary", type: "text", required: true, label: "路线摘要" },
        { key: "estimated_budget", type: "text", required: true, label: "预算" },
        { key: "days", type: "itinerary_builder", label: "每日行程" },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
  };

  App.TIME_SLOT_OPTIONS = TIME_SLOT_OPTIONS;
})();
