/* ChinaGo Admin — table schema definitions */

(function () {
  const App = window.ChinaGoAdmin;

  const CATEGORY_OPTIONS = ["palace", "temple", "park", "museum", "wall", "garden", "sight", "market", "other"];
  const PRIORITY_OPTIONS = ["P0", "P1", "P2"];
  const WEEKDAY_OPTIONS = [
    { value: "mon", label: "Mon" },
    { value: "tue", label: "Tue" },
    { value: "wed", label: "Wed" },
    { value: "thu", label: "Thu" },
    { value: "fri", label: "Fri" },
    { value: "sat", label: "Sat" },
    { value: "sun", label: "Sun" },
  ];
  const CHECKLIST_PHASE_OPTIONS = [
    { value: "before_departure", label: "出发前" },
    { value: "on_arrival", label: "抵达后" },
    { value: "during_trip", label: "行程中" },
  ];
  const CHECKLIST_TYPE_OPTIONS = [
    { value: "entry", label: "入境/签证 (Entry)" },
    { value: "universal", label: "通用 (Universal)" },
    { value: "city", label: "城市 (City)" },
  ];
  const CHECKLIST_PRIORITY_OPTIONS = [
    { value: "required", label: "必做" },
    { value: "recommended", label: "推荐" },
    { value: "optional", label: "可选" },
  ];
  const CHECKLIST_TAG_OPTIONS = [
    { value: "key", label: "Key（重点）" },
    { value: "urgent", label: "Urgent（紧急）" },
  ];

  App.CHECKLIST_TYPE_LABELS = Object.fromEntries(
    CHECKLIST_TYPE_OPTIONS.map((o) => [o.value, o.label])
  );
  App.CHECKLIST_PHASE_LABELS = Object.fromEntries(
    CHECKLIST_PHASE_OPTIONS.map((o) => [o.value, o.label])
  );
  App.CHECKLIST_PRIORITY_LABELS = Object.fromEntries(
    CHECKLIST_PRIORITY_OPTIONS.map((o) => [o.value, o.label])
  );
  const TIME_SLOT_OPTIONS = ["AM", "PM", "EVE"];

  App.TABLES = {
    app_settings: {
      label: "应用配置",
      single: true,
      groupedSections: true,
      pk: "id",
      order: null,
      fields: [
        { key: "id", type: "text", readonly: true, advanced: true },
        { key: "use_remote_content", type: "bool", label: "远程内容（Live Services）" },
        { key: "use_remote_ai", type: "bool", label: "远程 AI（开启后 App 调用 Edge Function）" },
        { key: "ai_section", type: "section", label: "大模型调用（火山引擎 Ark）", hint: "API Key 仅配置在 Supabase Edge Function Secrets，勿写入此处。保存后 Edge Function 每次请求会读取本页配置。" },
        { key: "ai_model_id", type: "text", label: "模型 Endpoint ID", hint: "火山方舟控制台 → 推理接入点 ID；留空则使用 Secrets 中的 VOLCENGINE_SUGGESTION_MODEL" },
        { key: "ai_chat_api_url", type: "text", label: "Chat API 地址", hint: "默认 https://ark.cn-beijing.volces.com/api/v3/chat/completions" },
        { key: "ai_chat_max_tokens", type: "number", label: "助手对话 max_tokens", hint: "建议 150–300，控制单次回复长度" },
        { key: "ai_itinerary_max_tokens", type: "number", label: "行程生成 max_tokens", hint: "建议 1000–1500" },
        { key: "ai_temperature", type: "number", label: "temperature（0–1）", hint: "0.7 为默认；越低越保守" },
        { key: "ai_timeout_ms", type: "number", label: "请求超时（毫秒）", hint: "建议 20000（20 秒）" },
        { key: "ai_system_prompt_assistant", type: "textarea", label: "助手 System Prompt", hint: "控制助手人设、回复风格与长度规则。修改后立即生效（缓存 5 分钟）" },
        { key: "ai_system_prompt_itinerary", type: "textarea", label: "行程 System Prompt", hint: "模型只输出 assignments（attraction_id+day）与 experience_days，不得编造 catalog 外景点" },
        {
          key: "iap_section",
          type: "section",
          label: "内购与试听",
          hint: "开启「远程内购」后 App 未购买用户可试听 free_audio_preview_seconds 秒；购买按钮引导登录（尚无 StoreKit）。关闭时 App 视为全员已解锁，便于本地演示。",
        },
        {
          key: "use_remote_iap",
          type: "bool",
          label: "远程内购（锁定未购景点）",
          hint: "true：未购仅试听；false：开发模式，跳过付费墙",
        },
        {
          key: "free_audio_preview_seconds",
          type: "number",
          label: "免费试听秒数",
          hint: "默认 180（3 分钟）。主景点与子区域未解锁时共用此上限。",
        },
        {
          key: "free_text_preview_chars",
          type: "number",
          label: "免费文字预览字符数",
          hint: "付费墙前展示的纯文本字符数，默认 80。",
        },
        {
          key: "free_visitor_tips_count",
          type: "number",
          label: "免费展示访客贴士条数",
          hint: "未付费时展示的访客贴士条数，默认 1。",
        },
        { key: "support_email", type: "text", label: "反馈邮箱" },
        { key: "about_title", type: "text", label: "关于 · 标题" },
        { key: "about_version", type: "text", label: "关于 · 版本号" },
        { key: "about_body", type: "richtext", label: "关于 · 简介" },
        { key: "assistant_greeting_general", type: "textarea", label: "助手 · 通用问候" },
        { key: "assistant_greeting_planning", type: "textarea", label: "助手 · 规划问候" },
        { key: "plan_alert_message", type: "textarea", label: "Plan · 顶部警告文案" },
        { key: "plan_alert_link_city_id", type: "ref_city", label: "Plan · 警告链接城市", allowEmpty: true },
        { key: "plan_alert_link_attraction_id", type: "ref_attraction", label: "Plan · 警告链接景点", allowEmpty: true, filterByCityField: "plan_alert_link_city_id" },
        { key: "plan_alert_link_label", type: "text", label: "Plan · 警告链接按钮文案" },
        {
          key: "paywall_section",
          type: "section",
          label: "Paywall 文案（解锁弹窗）",
          hint: "付费墙弹窗的会员计划、价格、权益、试用均来自「会员计划」表，此处仅控制少量通用文案。",
        },
        { key: "paywall_preview_line_template", type: "text", label: "预览行模板", hint: "支持 {duration}" },
        { key: "paywall_restore", type: "text", label: "恢复购买" },
        { key: "paywall_footnote", type: "textarea", label: "底部说明" },
        { key: "flight_section", type: "section", label: "机票平台链接" },
        { key: "flight_platforms", type: "flight_platform_list", label: "机票预订平台" },
      ],
    },
    assistant_scenarios: {
      label: "助手场景",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "label", label: "显示名称" },
        { key: "id", label: "场景 ID", advanced: true },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "label", type: "text", required: true, label: "显示名称", hint: "如「🚇 地铁」「租车指南」" },
        { key: "id", type: "slug", slugSource: "label", slugPrefix: "scene", required: true },
        { key: "description", type: "textarea", label: "说明（可选）" },
        { key: "user_message_template", type: "textarea", label: "用户气泡文案", hint: "点击芯片后显示给用户的消息" },
        { key: "ai_system_prompt", type: "textarea", label: "AI System Prompt", hint: "该场景专用，与全局助手 Prompt 合并" },
        { key: "response_mode", type: "enum", options: [
          { value: "ai", label: "调用 AI" },
          { value: "offline", label: "离线（不调 AI）" },
        ], label: "响应模式" },
        { key: "sort_order", type: "number", label: "排序" },
        { key: "is_active", type: "bool", label: "启用", defaultTrue: true },
      ],
    },
    assistant_chips: {
      label: "助手快捷芯片",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "label", label: "标签" },
        { key: "scenario_id", label: "场景", ref: "scenario" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "label", slugPrefix: "chip", required: true },
        { key: "scenario_id", type: "ref_scenario", required: true, label: "助手场景" },
        { key: "label", type: "text", required: true, label: "显示文字" },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    cities: {
      label: "城市",
      pk: "id",
      order: "display_order",
      listColumns: [
        { key: "name", label: "英文名" },
        { key: "chinese_name", label: "中文名" },
        { key: "emoji", label: "表情" },
        { key: "is_published", label: "已发布" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "name", required: true },
        { key: "name", type: "text", required: true, label: "英文名" },
        { key: "chinese_name", type: "text", required: true, label: "中文名" },
        { key: "emoji", type: "text", label: "表情符号" },
        { key: "cover_image_path", type: "image_preview", label: "封面图" },
        { key: "_cover_upload", type: "image_upload", label: "上传封面", uploadFolder: "cities", uploadTarget: "cover_image_path" },
        {
          key: "description",
          type: "richtext",
          label: "简介",
          uploadFolder: "cities",
          uploadSlugSource: "name",
        },
        { key: "best_for", type: "tags", label: "适合人群（逗号分隔）" },
        { key: "season_note", type: "text", label: "季节提示" },
        { key: "best_time_to_visit", type: "text", label: "最佳游览时间" },
        { key: "avg_days_recommended", type: "number", label: "推荐天数" },
        { key: "attraction_count", type: "number", label: "景点数量" },
        { key: "display_order", type: "number", label: "排序" },
        { key: "is_published", type: "bool", label: "已发布" },
      ],
    },
    city_guides: {
      label: "城市指南",
      pk: "id",
      order: "display_order",
      listColumns: [
        { key: "title_en", label: "标题" },
        { key: "badge", label: "标签" },
        { key: "display_order", label: "排序" },
        { key: "audio_url", label: "音频", format: "has_audio" },
        { key: "is_published", label: "已发布" },
      ],
      fields: [
        { key: "title_en", type: "text", required: true, label: "英文标题" },
        { key: "title_zh", type: "text", label: "中文标题" },
        { key: "city_id", type: "ref_city", required: true, label: "所属城市" },
        { key: "id", type: "slug", slugSource: "title_en", slugPrefix: "cg", slugPrefixField: "city_id", required: true },
        { key: "subtitle", type: "text", label: "列表副标题" },
        { key: "icon", type: "text", label: "图标（emoji）", hint: "如 ✦ 🚶 ☀" },
        { key: "badge", type: "text", label: "标签", hint: "如 Citywalk" },
        {
          key: "cover_images",
          type: "image_url_list",
          label: "详情轮播图",
          uploadFolder: "city-guides",
          uploadPrimary: true,
          hint: "详情页顶部轮播；可上传多张",
        },
        {
          key: "body",
          type: "richtext",
          label: "详情正文（富文本）",
          uploadFolder: "city-guides",
          uploadSlugSource: "title_en",
          uploadSlugPrefixField: "city_id",
        },
        {
          key: "meta_items",
          type: "practical_info_list",
          label: "详情 Meta 信息",
          hint: "可自由增删条目；图标、字段名（标签）、内容均可自定义，App 详情页标题下方展示",
          presets: [
            { icon: "⏱", label: "Duration" },
            { icon: "📏", label: "Distance" },
            { icon: "📍", label: "Stops" },
          ],
        },
        {
          key: "audio_section",
          type: "section",
          label: "详情页音频",
          hint: "选择本地文件后立即上传；上传后请点击保存",
        },
        { key: "audio_title", type: "text", label: "音频标题" },
        { key: "audio_url", type: "audio_preview", label: "当前音频" },
        {
          key: "_cg_audio_upload",
          type: "audio_upload",
          label: "本地上传音频",
          cityGuideDirect: true,
          hint: "路径 audio-guides/city-guides/{指南id}.m4a",
        },
        { key: "audio_duration_seconds", type: "number", label: "音频时长（秒）" },
        { key: "audio_quote", type: "richtext", label: "音频预览引文" },
        { key: "audio_transcript", type: "richtext", label: "音频文字稿" },
        { key: "display_order", type: "number", label: "排序" },
        { key: "is_published", type: "bool", label: "已发布", defaultTrue: true },
      ],
    },
    attractions: {
      label: "景点",
      pk: "id",
      order: "display_order",
      listColumns: [
        { key: "name", label: "名称" },
        { key: "city_id", label: "城市", ref: "city" },
        { key: "priority", label: "优先级" },
        { key: "is_published", label: "已发布" },
      ],
      fields: [
        { key: "name", type: "text", required: true, label: "英文名" },
        { key: "chinese_name", type: "text", required: true, label: "中文名" },
        { key: "city_id", type: "ref_city", required: true, label: "所属城市" },
        { key: "category", type: "enum", options: CATEGORY_OPTIONS, label: "类型" },
        { key: "summary", type: "richtext", label: "摘要" },
        { key: "short_description", type: "richtext", label: "短描述 (v2)" },
        {
          key: "introduction",
          type: "richtext",
          label: "书面解说（长文）",
          uploadFolder: "attractions",
          uploadSlugSource: "name",
          uploadSlugPrefixField: "city_id",
        },
        { key: "address_en", type: "text", label: "地址（英文）" },
        { key: "address_zh", type: "text", label: "地址（中文）" },
        {
          key: "iap_attraction_section",
          type: "section",
          label: "付费墙（景点级）",
          hint: "默认免费。开启「需要付费墙」后，此景点的音频+图文需购买或会员解锁。价格档在「景点定价」面板统一配置，也可在此选择。",
        },
        {
          key: "requires_purchase",
          type: "bool",
          label: "需要付费墙",
          hint: "开启后此景点的 Guide（音频+文字）需购买或会员解锁；关闭=全部免费。也可在「景点定价」面板批量设置。",
        },
        {
          key: "cover_images",
          type: "image_url_list",
          label: "多图",
          uploadFolder: "attractions",
          uploadPrimary: true,
          hint: "点击「本地上传」选择一张或多张；保存时自动上传至 Storage。也可粘贴已有 URL。",
        },
        { key: "priority", type: "enum", options: PRIORITY_OPTIONS, label: "优先级" },
        {
          key: "planning_time_section",
          type: "section",
          label: "行程规划 · 开放时间",
          hint: "结构化维护闭馆日与开闭馆时段；保存时会自动同步 Opening Hours / Closed 文案到实用信息",
        },
        { key: "planning_zone", type: "text", label: "规划分区（planning_zone）", hint: "如 palace_core / old_city_west，用于同日顺路分区" },
        { key: "closed_weekdays", type: "weekday_multiselect", options: WEEKDAY_OPTIONS, label: "固定闭馆周几" },
        { key: "open_time", type: "time", label: "开馆时间（HH:MM）" },
        { key: "close_time", type: "time", label: "闭馆时间（HH:MM）" },
        { key: "last_entry_time", type: "time", label: "最晚入场（HH:MM）" },
        { key: "opening_hours", type: "text", label: "Opening Hours 文案（自动生成，可覆盖）" },
        { key: "closed_days", type: "text", label: "Closed 文案（自动生成，可覆盖）" },
        {
          key: "practical_section",
          type: "section",
          label: "实用信息",
          hint: "门票、时长、开放时间等；可增删条目，保存后 App 详情页展示",
        },
        {
          key: "practical_info",
          type: "practical_info_list",
          label: "实用信息条目",
          presets: [
            { icon: "🎫", label: "Ticket" },
            { icon: "🕐", label: "Duration" },
            { icon: "🕘", label: "Opening Hours" },
            { icon: "❌", label: "Closed" },
            { icon: "🚇", label: "Metro" },
          ],
        },
        { key: "requires_advance_booking", type: "bool", label: "需提前预约" },
        { key: "western_visitor_tips", type: "string_list", label: "西方游客贴士" },
        { key: "nearby_places", type: "place_list", label: "周边推荐" },
        { key: "cover_image_path", type: "image_preview", label: "封面图" },
        { key: "_cover_upload", type: "image_upload", label: "上传封面", uploadFolder: "attractions", uploadTarget: "cover_image_path" },
        { key: "is_published", type: "bool", label: "已发布", defaultTrue: true },
        { key: "display_order", type: "number", label: "排序" },
        { key: "id", type: "slug", slugSource: "name", slugPrefixField: "city_id", required: true },
        {
          key: "audio_guide_count",
          type: "number",
          label: "音频导览数",
          advanced: true,
          computed: true,
          readonly: true,
        },
      ],
    },
    sub_areas: {
      label: "景点子区域",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "name_en", label: "名称" },
        { key: "attraction_id", label: "景点", ref: "attraction" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "attraction_id", type: "ref_attraction", required: true, label: "所属景点" },
        { key: "name_en", type: "text", required: true, label: "英文名" },
        { key: "name_zh", type: "text", label: "中文名" },
        { key: "cover_image_path", type: "image_preview", label: "封面图" },
        { key: "_cover_upload", type: "image_upload", label: "上传封面", uploadFolder: "attractions", uploadTarget: "cover_image_path" },
        {
          key: "body",
          type: "richtext",
          label: "正文内容",
          uploadFolder: "sub-areas",
          uploadEntityField: "id",
          uploadSlugSource: "name_en",
          uploadSlugPrefix: "area",
          hint: "整页图文说明；工具栏可本地上传图片（需先填写英文名）。旧版分块会自动合并",
        },
        {
          key: "audio_section",
          type: "section",
          label: "展区音频",
          hint: "选择本地文件后立即上传；上传成功后请点击「保存子区域」",
        },
        { key: "audio_url", type: "audio_preview", label: "当前音频" },
        {
          key: "_sa_audio_upload",
          type: "audio_upload",
          label: "本地上传音频",
          subAreaDirect: true,
          hint: "路径 audio-guides/sub-areas/{子区域id}.m4a",
        },
        {
          key: "sub_paywall_section",
          type: "section",
          label: "付费墙（子区域级）",
          hint: "默认免费。开启后此子区域需购买或会员解锁；买父景点也会自动解锁。价格档在「景点定价」面板配置。",
        },
        {
          key: "requires_purchase",
          type: "bool",
          label: "需要付费墙",
          hint: "开启后此子区域的音频+图文需购买；买父景点或会员可解锁。也可在「景点定价」面板批量设置。",
        },
        { key: "sort_order", type: "number", label: "排序" },
        { key: "is_active", type: "bool", label: "启用", defaultTrue: true },
        { key: "id", type: "slug", slugSource: "name_en", slugPrefix: "area", required: true },
      ],
    },
    checklist_items: {
      label: "行前清单",
      pk: "id",
      order: "sort_order",
      typeFilter: true,
      listColumns: [
        { key: "title_en", label: "标题" },
        { key: "type", label: "类型", format: "checklist_type" },
        { key: "group_title", label: "分组" },
        { key: "target_nationalities", label: "目标国籍", ref: "countries" },
        { key: "target_cities", label: "目标城市", ref: "cities" },
        { key: "priority", label: "优先级", format: "checklist_priority" },
        { key: "sort_order", label: "排序" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        {
          key: "_checklist_arch",
          type: "section",
          label: "三类清单（与 App Prepare 一致）",
          hint: "入境 entry：按护照国籍，有账号即可见，与行程无关。通用 universal：全员可见。城市 city：用户保存行程且城市匹配后才出现。App 排序：entry → universal → city。",
        },
        { key: "type", type: "enum", options: CHECKLIST_TYPE_OPTIONS, required: true, label: "清单类型" },
        { key: "phase", type: "enum", options: CHECKLIST_PHASE_OPTIONS, required: true, label: "阶段", advanced: true, hint: "App 当前按 type 分组，phase 仅作运营备注" },
        { key: "priority", type: "enum", options: CHECKLIST_PRIORITY_OPTIONS, required: true, label: "优先级" },
        {
          key: "group_title",
          type: "text",
          required: true,
          label: "分组标题",
          hint: "entry/universal 可填 Entry Requirements、Essential Prep；city 建议用城市名如 Beijing",
        },
        { key: "title_en", type: "text", required: true, label: "英文标题" },
        {
          key: "target_nationalities",
          type: "ref_countries_multi",
          label: "目标国籍",
          hint: "仅入境类型：不选 = 对所有国籍显示；选了则仅匹配护照国家",
          showWhen: { field: "type", values: ["entry"] },
        },
        {
          key: "target_cities",
          type: "ref_cities_multi",
          label: "目标城市",
          hint: "仅城市类型：与行程中的城市匹配才展示；不选则不会出现在任何行程清单中",
          showWhen: { field: "type", values: ["city"] },
        },
        {
          key: "city_id",
          type: "ref_city",
          label: "主城市（兼容旧版）",
          allowEmpty: true,
          emptyLabel: "无",
          advanced: true,
          showWhen: { field: "type", values: ["city"] },
        },
        { key: "why_important", type: "richtext", label: "为何重要" },
        { key: "how_to_complete", type: "richtext", label: "如何完成" },
        { key: "external_links", type: "link_list", label: "外链（按钮 + URL）" },
        { key: "estimated_minutes", type: "number", label: "预计分钟", allowNull: true },
        {
          key: "display_tags",
          type: "enum_multi",
          options: CHECKLIST_TAG_OPTIONS,
          label: "展示标签",
          hint: "App 内 Key / Urgent 角标",
        },
        { key: "cultural_tip", type: "richtext", label: "文化提示" },
        { key: "sort_order", type: "number", label: "排序" },
        { key: "is_active", type: "bool", label: "启用", defaultTrue: true },
        { key: "id", type: "slug", slugSource: "title_en", slugPrefix: "cl", required: true },
      ],
    },
    checklist_settings: {
      label: "清单全局设置",
      single: true,
      pk: "id",
      order: null,
      fields: [
        { key: "id", type: "text", readonly: true, advanced: true },
        {
          key: "_prep_settings",
          type: "section",
          label: "Prepare 提醒",
          hint: "变量：{days} 距出发天数，{count} 未完成条目数。推送需用户在 Profile 开启 Trip reminders；Prepare 页黄色横幅由 home_banner_enabled 控制。",
        },
        { key: "reminder_days", type: "number", label: "出发前提醒天数", hint: "默认 3：出发日 ≤ 该天数且仍有未完成项时触发" },
        { key: "push_title", type: "text", label: "推送标题模板", hint: "例：Your China trip is in {days} days!" },
        { key: "push_body", type: "textarea", label: "推送正文模板", hint: "例：You still have {count} prep items to complete." },
        { key: "home_banner_enabled", type: "bool", label: "Prepare 内横幅启用" },
        {
          key: "home_banner_template",
          type: "textarea",
          label: "Prepare 横幅模板（备用）",
          advanced: true,
          hint: "App 当前使用固定英文横幅；此字段预留给后续本地化",
        },
      ],
    },
    home_tips: {
      label: "首页提示",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "headline", label: "标题" },
        { key: "city_id", label: "城市", ref: "city" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "headline", slugPrefix: "tip", required: true },
        { key: "city_id", type: "ref_city", label: "城市", allowEmpty: true },
        { key: "kicker", type: "text", label: "角标" },
        { key: "headline", type: "text", required: true, label: "主标题" },
        { key: "body", type: "richtext", required: true, label: "正文" },
        { key: "link_label", type: "text", label: "链接按钮文字" },
        { key: "link_attraction_id", type: "ref_attraction", label: "链接景点", allowEmpty: true, filterByCityField: "city_id" },
        { key: "link_url", type: "text", label: "外链 URL" },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    audio_guides: {
      label: "音频导览",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "title_en", label: "标题" },
        { key: "attraction_id", label: "景点", ref: "attraction" },
        { key: "audio_url", label: "音频", format: "has_audio" },
        { key: "duration_seconds", label: "时长", format: "duration_mmss" },
        { key: "is_main_guide", label: "主线路" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "title_en", type: "text", required: true, label: "标题" },
        { key: "attraction_id", type: "ref_attraction", required: true, label: "所属景点" },
        { key: "id", type: "slug", slugSource: "title_en", slugPrefix: "ag", required: true },
        { key: "description", type: "richtext", label: "说明" },
        {
          key: "duration_seconds",
          type: "number",
          label: "时长（秒）",
          hint: "上传 MP3 后可自动填入；Paywall 预览行模板中的 {duration} 亦依赖此值",
        },
        { key: "audio_url", type: "audio_preview", label: "当前音频" },
        {
          key: "_audio_upload",
          type: "audio_upload",
          label: "上传音频",
          hint: "选择文件后立即上传至 audio-guides/{导览id}.m4a；上传后请点击保存",
        },
        { key: "quote", type: "richtext", label: "开场引文" },
        { key: "segments", type: "segment_list", label: "章节时间轴" },
        { key: "is_main_guide", type: "bool", label: "主线路" },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    shopping_items: {
      label: "购物清单",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "title_en", label: "标题" },
        { key: "city_id", label: "城市", ref: "city" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "title_en", slugPrefix: "shop", required: true },
        { key: "city_id", type: "ref_city", label: "城市", allowEmpty: true, emptyLabel: "全局" },
        { key: "title_en", type: "text", required: true },
        { key: "note_en", type: "richtext" },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    reading_list: {
      label: "阅读清单",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "title", label: "书名" },
        { key: "author", label: "作者" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "title", slugPrefix: "read", required: true },
        { key: "city_ids", type: "ref_cities_multi", label: "关联城市" },
        { key: "title", type: "text", required: true },
        { key: "author", type: "text", required: true },
        { key: "genre", type: "text", required: true },
        { key: "synopsis_en", type: "richtext", required: true },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    hotels: {
      label: "酒店",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "name", label: "名称" },
        { key: "city_id", label: "城市", ref: "city" },
        { key: "cover_image_path", label: "封面", type: "image_thumb" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "name", slugPrefix: "hotel", slugPrefixField: "city_id", required: true },
        { key: "city_id", type: "ref_city", required: true, label: "城市" },
        { key: "name", type: "text", required: true },
        { key: "chinese_name", type: "text", required: true },
        { key: "cover_image_path", type: "image_preview", label: "封面图" },
        { key: "_cover_upload", type: "image_upload", label: "上传封面", uploadFolder: "hotels", uploadTarget: "cover_image_path" },
        { key: "address_en", type: "text", label: "地址（英文，App 展示 + 导航）" },
        { key: "address_zh", type: "text", label: "地址（中文，导航优先）" },
        { key: "latitude", type: "number", label: "纬度（可选，精确导航）", allowNull: true },
        { key: "longitude", type: "number", label: "经度（可选，精确导航）", allowNull: true },
        { key: "stars", type: "number", label: "星级" },
        { key: "price_min_usd", type: "number", label: "最低价 USD" },
        { key: "has_english_staff", type: "bool", label: "有英语服务" },
        { key: "english_staff_note", type: "richtext" },
        { key: "language_tip", type: "richtext" },
        { key: "location_note", type: "richtext" },
        { key: "booking_platforms", type: "tags", label: "预订平台（legacy 标签）" },
        { key: "booking_links", type: "link_list", label: "预订链接" },
        { key: "accepts_foreigners", type: "bool", label: "接待外国客人", defaultTrue: true },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用", defaultTrue: true },
      ],
    },
    passport_countries: {
      label: "护照国家",
      pk: "code",
      order: "display_order",
      listColumns: [
        { key: "code", label: "代码" },
        { key: "name", label: "名称" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "code", type: "text", required: true, label: "国家代码（如 GB）" },
        { key: "name", type: "text", required: true },
        { key: "flag", type: "text", label: "国旗 emoji" },
        { key: "display_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    visa_rules: {
      label: "签证规则",
      pk: "country_code",
      order: "country_code",
      listColumns: [
        { key: "country_code", label: "国家", ref: "country" },
        { key: "headline", label: "标题" },
        { key: "visa_free", label: "免签" },
      ],
      fields: [
        { key: "country_code", type: "ref_country", required: true, label: "国家" },
        { key: "country_name", type: "text", required: true, label: "国家名（自动建议）", autoFromCountry: true },
        { key: "flag", type: "text", label: "国旗" },
        { key: "visa_free", type: "bool", label: "免签" },
        { key: "stay_days", type: "number", label: "停留天数" },
        { key: "headline", type: "text", required: true },
        { key: "details", type: "visa_detail_list", label: "详情条目" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    culture_tips: {
      label: "文化贴士",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "title", label: "标题" },
        { key: "category", label: "分类" },
        { key: "city_id", label: "城市", ref: "city" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "title", slugPrefix: "culture", required: true },
        { key: "emoji", type: "text" },
        { key: "city_id", type: "ref_city", allowEmpty: true, emptyLabel: "通用（所有城市）", label: "城市（空=通用）" },
        { key: "category", type: "enum", options: [
          { value: "food", label: "Food & Dining" },
          { value: "payments", label: "Payments & Money" },
          { value: "temple", label: "Temple & Sacred Sites" },
          { value: "transport", label: "Transportation" },
          { value: "social", label: "Social Etiquette" },
          { value: "festivals", label: "Festivals & Holidays" },
        ], required: true, label: "分类" },
        { key: "title", type: "text", required: true },
        { key: "preview", type: "richtext", required: true },
        {
          key: "body",
          type: "richtext",
          required: true,
          uploadFolder: "culture-tips",
          uploadSlugSource: "title",
          uploadSlugPrefix: "culture",
        },
        { key: "do_text", type: "richtext", label: "Do（建议）" },
        { key: "dont_text", type: "richtext", label: "Don't（避免）" },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    assistant_replies: {
      label: "助手回复",
      pk: "scenario_id",
      order: "scenario_id",
      listColumns: [
        { key: "scenario_id", label: "场景", ref: "scenario" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "scenario_id", type: "ref_scenario", required: true, label: "助手场景" },
        { key: "user_message", type: "textarea", label: "用户消息示例" },
        { key: "assistant_message", type: "textarea", required: true, label: "助手回复" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    emergency_config: {
      label: "紧急联系",
      single: true,
      pk: "id",
      order: null,
      fields: [
        { key: "id", type: "text", readonly: true, advanced: true },
        { key: "embassy_note", type: "richtext", required: true, label: "使馆说明" },
        { key: "contacts", type: "contact_list", label: "紧急电话" },
        { key: "help_phrases", type: "help_phrase_list", label: "应急短语（中/拼/英）" },
      ],
    },
    content_itineraries: {
      label: "行程模板 (CMS)",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "title", label: "标题" },
        { key: "kind", label: "类型" },
        { key: "route_summary", label: "路线" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "title", slugPrefix: "itin", required: true },
        { key: "kind", type: "enum", options: [
          { value: "sample", label: "示例行程 (sample)" },
          { value: "planning", label: "规划草案 (planning)" },
        ], required: true, label: "类型", hint: "sample：新用户默认行程；planning：规划助手草案" },
        { key: "title", type: "text", required: true },
        { key: "meta", type: "text", required: true, label: "元信息（日期·风格）" },
        { key: "route_summary", type: "text", required: true, label: "路线摘要" },
        { key: "estimated_budget", type: "text", required: true, label: "预算文案" },
        { key: "days", type: "itinerary_builder", label: "每日行程", hint: "可添加多天、多活动；关联景点后 App 可跳转导览" },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    user_itineraries: {
      label: "用户行程",
      pk: "id",
      order: "updated_at",
      orderDesc: true,
      noCreate: true,
      noDelete: true,
      listColumns: [
        { key: "title", label: "标题" },
        { key: "user_id", label: "用户邮箱", format: "user_email" },
        { key: "cities", label: "城市" },
        { key: "is_deleted", label: "已删" },
        { key: "updated_at", label: "更新" },
      ],
      fields: [
        { key: "id", type: "text", readonly: true, advanced: true },
        { key: "user_id", type: "text", readonly: true, label: "用户 UUID" },
        { key: "title", type: "text", required: true, label: "行程标题" },
        { key: "meta", type: "text", label: "元信息（日期·风格）", hint: "存于 payload.meta" },
        { key: "route_summary", type: "text", label: "路线摘要", hint: "存于 payload.route_summary" },
        { key: "estimated_budget", type: "text", label: "预算文案", hint: "存于 payload.estimated_budget" },
        { key: "start_date", type: "text", label: "开始日期", hint: "YYYY-MM-DD，可选" },
        { key: "end_date", type: "text", label: "结束日期", hint: "YYYY-MM-DD，可选" },
        { key: "cities", type: "ref_cities_multi", label: "涉及城市" },
        { key: "days", type: "itinerary_builder", label: "每日行程", hint: "保存时写入 payload.days" },
        { key: "is_deleted", type: "bool", label: "软删除" },
      ],
    },

    // ════════════════════ 签证引擎 v2（已核验交付包 · engine.py 同构数据源）════════════════════
    visa_policies_v2: {
      label: "政策框架 v2",
      pk: "id",
      order: "priority",
      listColumns: [
        { key: "id", label: "政策 ID" },
        { key: "policy_type", label: "类型" },
        { key: "max_stay_default", label: "停留" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "text", required: true, label: "政策 ID", hint: "如 mutual_exempt / unilateral_30d / twov_240h / visa_L" },
        { key: "policy_type", type: "text", required: true, label: "政策类型", hint: "互免 / 单方面免签 / 过境免签 / 区域免签 / 团体免签 / 普通签证" },
        { key: "node_kind", type: "enum", label: "节点性质", default: "computed", options: [
          { value: "computed", label: "computed（参与计算）" },
          { value: "info", label: "info（兜底信息卡，不算离境）" },
        ] },
        { key: "official_name_zh", type: "text", label: "官方名 中文" },
        { key: "official_name_en", type: "text", label: "官方名 EN" },
        { key: "universal", type: "bool", label: "通用 universal", hint: "=开：世界各国通用（24h/邮轮），引擎跳过 grant 要求" },
        { key: "_cond_section", type: "section", label: "条件门槛（conditions_count = 以下 4 项之和）" },
        { key: "onward_ticket", type: "bool", label: "需续程票 onward_ticket" },
        { key: "onward_third_country", type: "bool", label: "需去第三国 onward_third_country" },
        { key: "group_required", type: "bool", label: "需随团 group_required" },
        { key: "entry_port_limited", type: "bool", label: "限口岸 entry_port_limited", hint: "不变式：=开 当且仅当 entry_ports 非空" },
        { key: "entry_ports", type: "ref_ports_multi", label: "入境口岸（从口岸维表勾选；空=不限）", hint: "选项来自「口岸维表（IATA）」，与检测器选择器同源，避免敲错码破坏命名空间。海港邮轮母港也在表内可选。" },
        { key: "exit_ports", type: "ref_ports_multi", label: "出境口岸（240h 出境同样受限；空=不限）", hint: "同上，从口岸维表勾选。" },
        { key: "entry_mode", type: "string_list", label: "入境方式（air/land/sea/cruise）" },
        { key: "purpose", type: "enum_multi", label: "入境目的 purpose", options: [
          { value: "tourism", label: "旅游 tourism" },
          { value: "business", label: "商务 business" },
          { value: "transit", label: "过境 transit" },
          { value: "family", label: "探亲 family" },
        ] },
        { key: "passport_ordinary_only", type: "bool", label: "仅普通护照 passport_ordinary_only", hint: "=开：仅持普通护照适用（外交/公务护照另有协定）", defaultTrue: true },
        { key: "_stay_section", type: "section", label: "停留与计时" },
        { key: "max_stay_default", type: "number", label: "默认停留上限", allowNull: true },
        { key: "max_stay_unit", type: "enum", label: "停留单位", options: [
          { value: "days", label: "天 days" },
          { value: "hours", label: "小时 hours" },
        ] },
        { key: "clock_rule", type: "enum", label: "计时规则", options: [
          { value: "next_day_0000", label: "入境次日 0 时起算 next_day_0000" },
          { value: "by_hour", label: "入境精确时刻 by_hour（24h 过境）" },
          { value: "entry_day", label: "入境当日 entry_day（兼容保留）" },
        ] },
        { key: "entry_count", type: "enum", label: "入境次数 entry_count", options: [
          { value: "single", label: "单次 single" },
          { value: "double", label: "两次 double" },
          { value: "multiple", label: "多次 multiple" },
          { value: "per_entry", label: "按每次入境计 per_entry" },
        ] },
        { key: "allowed_area", type: "json", label: "活动范围 allowed_area", hint: '"national" 或 行政区划码数组 ["110000","140100"]；24h 填 []' },
        { key: "passport_validity_months", type: "number", label: "护照有效期门槛（月）", hint: "GATE0，默认 6" },
        { key: "priority", type: "number", required: true, label: "优先级", hint: "仅兜底/展示序，不决定择优；visa_L=99" },
        { key: "source_url", type: "text", label: "一级信源 URL" },
        { key: "last_verified", type: "text", label: "核验日 YYYY-MM-DD" },
        { key: "is_active", type: "bool", label: "启用", defaultTrue: true },
      ],
    },
    visa_policy_grants_v2: {
      label: "政策适用 v2（国籍×窗口）",
      pk: "id",
      order: "id",
      listColumns: [
        { key: "policy_id", label: "政策" },
        { key: "country_code", label: "国家", ref: "visa_country" },
        { key: "effective_date", label: "生效" },
        { key: "expiry_date", label: "截止" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "text", required: true, label: "ID", hint: "唯一，如 unilateral_30d_fr" },
        { key: "policy_id", type: "ref_visa_policy_v2", required: true, label: "政策", hint: "下拉自动同步「政策框架 v2」，新建政策后无需改代码即可在此选到" },
        { key: "country_code", type: "ref_visa_country", required: true, label: "国家", hint: "选项来自「国家受控词表（ISO 249）」，全量 249 国/地区，非仅 90 免签国" },
        { key: "effective_date", type: "text", label: "生效日", hint: "YYYY-MM-DD；空/1900-01-01=无起始下限" },
        { key: "expiry_date", type: "text", label: "截止日", hint: "YYYY-MM-DD，空=官方未设截止（禁填假日期）" },
        { key: "max_stay_override", type: "number", label: "停留覆盖（天）", allowNull: true },
        { key: "entry_count_override", type: "enum", label: "入境次数覆盖", allowEmpty: true, emptyLabel: "— 不覆盖 —", options: [
          { value: "single", label: "单次 single" },
          { value: "double", label: "两次 double" },
          { value: "multiple", label: "多次 multiple" },
          { value: "per_entry", label: "按每次入境计 per_entry" },
        ] },
        { key: "announced_date", type: "text", label: "公告日 announced_date", hint: "YYYY-MM-DD" },
        { key: "source_url", type: "text", label: "公告信源 URL" },
        { key: "last_verified", type: "text", label: "核验日" },
        { key: "evidence_quote", type: "features_list", label: "原文引文 evidence_quote", hint: "采集自一级信源的原文（核对参照）" },
        { key: "is_active", type: "bool", label: "启用", defaultTrue: true },
      ],
    },
    visa_cities: {
      label: "城市维表 v2（GB/T 2260）",
      pk: "city_id",
      order: "city_id",
      listColumns: [
        { key: "city_id", label: "区划码" },
        { key: "name_zh", label: "中文名" },
        { key: "transit_240h", label: "240h" },
        { key: "app_city_slug", label: "App城市" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "city_id", type: "text", required: true, label: "区划码", hint: "GB/T 2260，如 上海 310000、苏州 320500" },
        { key: "name_zh", type: "text", required: true, label: "中文名" },
        { key: "name_en", type: "text", label: "英文名" },
        { key: "region_type", type: "enum", label: "区域类型", default: "mainland", options: [
          { value: "mainland", label: "内地 mainland" },
          { value: "special", label: "特殊区 special" },
        ] },
        { key: "is_entry_port", type: "bool", label: "可作入境口岸" },
        { key: "is_exit_port", type: "bool", label: "可作出境口岸" },
        { key: "transit_240h", type: "bool", label: "240h 过境覆盖" },
        { key: "app_city_slug", type: "ref_city", allowEmpty: true, emptyLabel: "— 无映射 —", label: "映射 App 内容城市", hint: "关联后检测器才能把该 App 城市翻成此区划码参与判定" },
        { key: "is_active", type: "bool", label: "启用", defaultTrue: true },
      ],
    },
    visa_config: {
      label: "引擎参数（可调）",
      pk: "key",
      order: "key",
      listColumns: [
        { key: "key", label: "键" },
        { key: "label_zh", label: "名称" },
        { key: "value_int", label: "整数值" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "key", type: "text", required: true, label: "参数键", hint: "如 passport_validity_months（护照最低有效期·月）。引擎按键读取，勿随意改键名" },
        { key: "label_zh", type: "text", label: "显示名" },
        { key: "value_int", type: "number", label: "整数值", hint: "护照最低有效期填月数（默认 3）。低于该值则不能免签、也办不了签证" },
        { key: "value_text", type: "text", label: "文本值（备用）" },
        { key: "is_active", type: "bool", label: "启用", defaultTrue: true },
      ],
    },
    visa_ports: {
      label: "口岸维表 v2（IATA）",
      pk: "code",
      order: "display_order",
      listColumns: [
        { key: "code", label: "码" },
        { key: "name_zh", label: "中文名" },
        { key: "port_type", label: "类型" },
        { key: "display_order", label: "排序" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "code", type: "text", required: true, label: "口岸码", hint: "空港 IATA 三字码（PVG/PEK）；水运/陆路用 UN/LOCODE（CNSHA）。须与政策 entry_ports/exit_ports 同命名空间，检测器与引擎按此匹配" },
        { key: "name_zh", type: "text", required: true, label: "中文名" },
        { key: "name_en", type: "text", label: "英文名" },
        { key: "port_type", type: "enum", label: "口岸类型 port_type", default: "air", options: [
          { value: "air", label: "空港 air" },
          { value: "sea", label: "水运 sea（邮轮母港）" },
          { value: "land", label: "陆路 land" },
        ] },
        { key: "city_id", type: "ref_city", allowEmpty: true, emptyLabel: "— 不关联 —", label: "所在城市（GB/T 2260）", hint: "供口岸↔城市联动校验" },
        { key: "display_order", type: "number", label: "排序", hint: "选择器从小到大排列" },
        { key: "is_active", type: "bool", label: "启用", defaultTrue: true },
      ],
    },
    visa_countries: {
      label: "国家受控词表（ISO 3166-1 · 249）",
      pk: "country_code",
      order: "country_code",
      listColumns: [
        { key: "country_code", label: "码" },
        { key: "flag_emoji", label: "旗" },
        { key: "name_zh", label: "中文名" },
        { key: "is_territory", label: "属地" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "country_code", type: "text", required: true, label: "ISO 二位码", hint: "ISO 3166-1 alpha-2，如 FR / US；grant 与护照国籍按此匹配" },
        { key: "name_zh", type: "text", required: true, label: "中文名" },
        { key: "name_en", type: "text", label: "英文名" },
        { key: "flag_emoji", type: "text", label: "国旗 emoji", hint: "由二位码生成，可留空" },
        { key: "is_territory", type: "bool", label: "非主权关境/属地", hint: "港澳台、海外属地等；用于 240h 第三地判定" },
        { key: "is_active", type: "bool", label: "启用", defaultTrue: true },
      ],
    },
    visa_permit_zones: {
      label: "许可区 v2（西藏等）",
      pk: "admin_code",
      order: "admin_code",
      listColumns: [
        { key: "admin_code", label: "区划码" },
        { key: "name", label: "名称" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "admin_code", type: "text", required: true, label: "区划码", hint: "GB/T 2260 省级/市级，如 西藏 540000" },
        { key: "name", type: "text", required: true, label: "名称" },
        { key: "note", type: "text", label: "备注", hint: "如「需入藏许可，覆盖所有政策」" },
        { key: "is_active", type: "bool", label: "启用", defaultTrue: true },
      ],
    },
    visa_city_policy_matrix: {
      label: "城市×政策矩阵 v2（派生·只读）",
      pk: "city_id",
      order: "policy_id",
      noCreate: true,
      noDelete: true,
      listColumns: [
        { key: "city_id", label: "城市" },
        { key: "policy_id", label: "政策" },
        { key: "feasibility", label: "可达性" },
      ],
      fields: [
        { key: "_derived_note", type: "section", label: "派生只读 · 自动同步", hint: "由 allowed_area 纯码匹配生成，不手填。改政策 allowed_area / 城市 / 许可区后，数据库触发器自动重算本表（铁律：派生由规则强制）。" },
        { key: "city_id", type: "text", readonly: true, label: "城市码" },
        { key: "policy_id", type: "text", readonly: true, label: "政策" },
        { key: "feasibility", type: "text", readonly: true, label: "可达性", hint: "ok / no / permit_required" },
        { key: "note", type: "text", readonly: true, label: "备注" },
      ],
    },

    // ════════════════════ 支付助手内容 ════════════════════
    payment_advice_rules: {
      label: "支付建议规则",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "dimension", label: "维度" },
        { key: "severity", label: "级别" },
        { key: "body_zh", label: "文案" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "dimension", slugPrefix: "pay", required: true },
        { key: "dimension", type: "enum", required: true, label: "维度", options: [
          { value: "sms", label: "短信/注册" },
          { value: "card", label: "绑卡" },
          { value: "cash", label: "现金" },
        ] },
        { key: "match_json", type: "payment_match", label: "匹配条件（不选任何项 = 对所有人显示）" },
        { key: "severity", type: "enum", label: "级别", options: [
          { value: "ok", label: "OK" },
          { value: "warn", label: "警告" },
          { value: "info", label: "信息" },
        ] },
        { key: "body_zh", type: "richtext", label: "文案 中文" },
        { key: "body_en", type: "richtext", label: "文案 EN" },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    payment_merchant_phrases: {
      label: "支付商家短语",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "cn", label: "中文" },
        { key: "en", label: "EN" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "en", slugPrefix: "mphrase", required: true },
        { key: "cn", type: "text", required: true, label: "中文" },
        { key: "en", type: "text", label: "EN" },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    payment_helper_links: {
      label: "支付外链",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "label_zh", label: "标签" },
        { key: "lane", label: "处境" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "label_en", slugPrefix: "paylink", required: true },
        { key: "label_zh", type: "text", required: true, label: "标签 中文" },
        { key: "label_en", type: "text", label: "标签 EN" },
        { key: "url", type: "text", required: true, label: "URL" },
        { key: "lane", type: "enum", label: "处境", options: [
          { value: "prep", label: "准备" },
          { value: "china", label: "已在中国" },
          { value: "rescue", label: "救援" },
        ] },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },

    // ════════════════════ 客服坐席（档案 + 强制状态）════════════════════
    support_agents: {
      label: "客服坐席",
      pk: "id",
      order: "display_order",
      listColumns: [
        { key: "name", label: "姓名" },
        { key: "role", label: "线路" },
        { key: "status", label: "状态" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "user_id", type: "ref_user", required: true, label: "登录账号（选邮箱）", hint: "下拉选择该客服的登录账号；在「用户管理」里能看到/创建账号" },
        { key: "name", type: "text", required: true, label: "姓名" },
        { key: "role", type: "text", label: "线路/专长", hint: "如 北京 · 签证" },
        { key: "avatar_seed", type: "text", label: "头像种子（首字）" },
        { key: "languages", type: "string_list", label: "语言" },
        { key: "status", type: "enum", label: "状态", default: "offline", hint: "通常由客服端手动切换；此处可强制", options: [
          { value: "online", label: "在线" },
          { value: "busy", label: "忙碌" },
          { value: "offline", label: "离线" },
        ] },
        { key: "avatar_url", type: "image_url", label: "头像（客服端可自己上传，也可在此设置）" },
        { key: "social_url", type: "text", label: "社交主页 URL" },
        { key: "display_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },

    support_conversations: {
      label: "客服会话（只读监控）",
      pk: "id",
      order: "updated_at",
      orderDesc: true,
      noCreate: true,
      noDelete: true,
      listColumns: [
        { key: "user_id", label: "用户", format: "user_email" },
        { key: "priority", label: "优先级" },
        { key: "status", label: "状态" },
        { key: "updated_at", label: "更新" },
      ],
      fields: [
        { key: "id", type: "text", readonly: true },
        { key: "user_id", type: "text", readonly: true, label: "用户 UUID" },
        { key: "agent_id", type: "text", readonly: true, label: "客服坐席 ID" },
        { key: "priority", type: "text", readonly: true },
        { key: "status", type: "text", readonly: true },
        { key: "context_json", type: "json", readonly: true, label: "上下文" },
        { key: "user_deleted_at", type: "text", readonly: true, label: "用户删除于（软删）" },
        { key: "agent_deleted_at", type: "text", readonly: true, label: "客服删除于（软删）" },
        { key: "created_at", type: "text", readonly: true },
        { key: "updated_at", type: "text", readonly: true },
      ],
    },
    support_messages: {
      label: "客服消息（只读监控）",
      pk: "id",
      order: "created_at",
      orderDesc: true,
      noCreate: true,
      noDelete: true,
      listColumns: [
        { key: "conversation_id", label: "会话" },
        { key: "sender_type", label: "发送方" },
        { key: "body_original", label: "原文" },
        { key: "created_at", label: "时间" },
      ],
      fields: [
        { key: "id", type: "text", readonly: true },
        { key: "conversation_id", type: "text", readonly: true },
        { key: "sender_type", type: "text", readonly: true },
        { key: "body_original", type: "textarea", readonly: true, label: "原文" },
        { key: "body_translated", type: "textarea", readonly: true, label: "译文" },
        { key: "image_url", type: "text", readonly: true, label: "图片路径" },
        { key: "created_at", type: "text", readonly: true },
      ],
    },

    // ════════════════════ 实用信息内容（交通 / 常用语 / 方言）════════════════════
    transport_tips: {
      label: "交通攻略",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "title_zh", label: "标题" },
        { key: "category", label: "分类" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "title_en", slugPrefix: "transport", required: true },
        { key: "category", type: "enum", required: true, label: "分类", options: [
          { value: "rail", label: "高铁" },
          { value: "taxi", label: "打车" },
          { value: "metro", label: "地铁" },
        ] },
        { key: "title_zh", type: "text", required: true, label: "标题 中文" },
        { key: "title_en", type: "text", label: "标题 EN" },
        { key: "body_zh", type: "richtext", label: "正文 中文" },
        { key: "body_en", type: "richtext", label: "正文 EN" },
        { key: "city_id", type: "ref_city", allowEmpty: true, emptyLabel: "通用", label: "城市（空=通用）" },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    internet_access_guides: {
      label: "科学上网指南",
      pk: "id",
      listColumns: [
        { key: "title_zh", label: "标题" },
        { key: "title_en", label: "标题 EN" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "text", required: true, label: "ID", hint: "固定 legal_guide，勿随意改" },
        { key: "title_zh", type: "text", required: true, label: "标题 中文" },
        { key: "title_en", type: "text", label: "标题 EN" },
        { key: "body_zh", type: "richtext", label: "正文 中文" },
        { key: "body_en", type: "richtext", label: "正文 EN" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    common_phrases: {
      label: "常用语",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "cn", label: "中文" },
        { key: "en", label: "EN" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "en", slugPrefix: "cphrase", required: true },
        { key: "cn", type: "text", required: true, label: "中文" },
        { key: "pinyin", type: "text", label: "拼音" },
        { key: "en", type: "text", label: "EN" },
        { key: "audio_url", type: "audio_preview", label: "当前音频" },
        {
          key: "_ph_audio_upload",
          type: "audio_upload",
          label: "上传音频",
          hint: "选择文件后立即上传至 audio-guides/phrases/{id}.m4a；上传后请点击保存（留空则 App 用系统朗读兜底）",
        },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
    dialect_phrases: {
      label: "方言彩蛋",
      pk: "id",
      order: "sort_order",
      listColumns: [
        { key: "dialect", label: "方言" },
        { key: "cn", label: "中文" },
        { key: "is_active", label: "启用" },
      ],
      fields: [
        { key: "id", type: "slug", slugSource: "cn", slugPrefix: "dphrase", required: true },
        { key: "dialect", type: "text", required: true, label: "方言", hint: "如 四川话 / 北京话 / 陕西话" },
        { key: "emoji", type: "text", label: "Emoji" },
        { key: "cn", type: "text", required: true, label: "中文" },
        { key: "pinyin", type: "text", label: "拼音" },
        { key: "en", type: "text", label: "EN" },
        { key: "audio_url", type: "audio_preview", label: "当前音频" },
        {
          key: "_ph_audio_upload",
          type: "audio_upload",
          label: "上传音频",
          hint: "选择文件后立即上传至 audio-guides/phrases/{id}.m4a；上传后请点击保存（留空则 App 用系统朗读兜底）",
        },
        { key: "sort_order", type: "number" },
        { key: "is_active", type: "bool", label: "启用" },
      ],
    },
  };

  App.PRACTICAL_INFO_PRESETS = [
    { icon: "🎫", label: "Ticket" },
    { icon: "🕐", label: "Duration" },
    { icon: "🕘", label: "Opening Hours" },
    { icon: "❌", label: "Closed" },
    { icon: "🚇", label: "Metro" },
  ];

  App.TIME_SLOT_OPTIONS = TIME_SLOT_OPTIONS;
})();
