-- Align content tables created before migration 004 (CREATE IF NOT EXISTS skips new columns).
-- Run this BEFORE 008_seed_content.sql if seed fails with "column does not exist".

-- cities
ALTER TABLE cities ADD COLUMN IF NOT EXISTS chinese_name TEXT;
ALTER TABLE cities ADD COLUMN IF NOT EXISTS emoji TEXT;
ALTER TABLE cities ADD COLUMN IF NOT EXISTS cover_image_path TEXT;
ALTER TABLE cities ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE cities ADD COLUMN IF NOT EXISTS best_for TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE cities ADD COLUMN IF NOT EXISTS season_note TEXT;
ALTER TABLE cities ADD COLUMN IF NOT EXISTS best_time_to_visit TEXT;
ALTER TABLE cities ADD COLUMN IF NOT EXISTS avg_days_recommended INT;
ALTER TABLE cities ADD COLUMN IF NOT EXISTS attraction_count INT NOT NULL DEFAULT 0;
ALTER TABLE cities ADD COLUMN IF NOT EXISTS display_order INT NOT NULL DEFAULT 0;
ALTER TABLE cities ADD COLUMN IF NOT EXISTS is_published BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE cities ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

UPDATE cities SET chinese_name = name WHERE chinese_name IS NULL;

-- city_routes
ALTER TABLE city_routes ADD COLUMN IF NOT EXISTS sort_order INT NOT NULL DEFAULT 0;
ALTER TABLE city_routes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- attractions
ALTER TABLE attractions ADD COLUMN IF NOT EXISTS chinese_name TEXT;
ALTER TABLE attractions ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'sight';
ALTER TABLE attractions ADD COLUMN IF NOT EXISTS cover_image_path TEXT;
ALTER TABLE attractions ADD COLUMN IF NOT EXISTS summary TEXT;
ALTER TABLE attractions ADD COLUMN IF NOT EXISTS introduction TEXT;
ALTER TABLE attractions ADD COLUMN IF NOT EXISTS priority TEXT NOT NULL DEFAULT 'P1';
ALTER TABLE attractions ADD COLUMN IF NOT EXISTS ticket_price TEXT;
ALTER TABLE attractions ADD COLUMN IF NOT EXISTS recommended_duration TEXT;
ALTER TABLE attractions ADD COLUMN IF NOT EXISTS opening_hours TEXT;
ALTER TABLE attractions ADD COLUMN IF NOT EXISTS closed_days TEXT;
ALTER TABLE attractions ADD COLUMN IF NOT EXISTS requires_advance_booking BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE attractions ADD COLUMN IF NOT EXISTS metro_access TEXT;
ALTER TABLE attractions ADD COLUMN IF NOT EXISTS western_visitor_tips JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE attractions ADD COLUMN IF NOT EXISTS nearby_places JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE attractions ADD COLUMN IF NOT EXISTS audio_guide_count INT NOT NULL DEFAULT 0;
ALTER TABLE attractions ADD COLUMN IF NOT EXISTS iap_product_id TEXT;
ALTER TABLE attractions ADD COLUMN IF NOT EXISTS display_order INT NOT NULL DEFAULT 0;
ALTER TABLE attractions ADD COLUMN IF NOT EXISTS is_published BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE attractions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- audio_guides
ALTER TABLE audio_guides ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE audio_guides ADD COLUMN IF NOT EXISTS duration_seconds INT NOT NULL DEFAULT 0;
ALTER TABLE audio_guides ADD COLUMN IF NOT EXISTS audio_url TEXT NOT NULL DEFAULT '';
ALTER TABLE audio_guides ADD COLUMN IF NOT EXISTS quote TEXT;
ALTER TABLE audio_guides ADD COLUMN IF NOT EXISTS segments JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE audio_guides ADD COLUMN IF NOT EXISTS is_main_guide BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE audio_guides ADD COLUMN IF NOT EXISTS sort_order INT NOT NULL DEFAULT 0;
ALTER TABLE audio_guides ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE audio_guides ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- checklist_items
ALTER TABLE checklist_items ADD COLUMN IF NOT EXISTS display_tags TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE checklist_items ADD COLUMN IF NOT EXISTS cultural_tip TEXT;
ALTER TABLE checklist_items ADD COLUMN IF NOT EXISTS sort_order INT NOT NULL DEFAULT 0;
ALTER TABLE checklist_items ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE checklist_items ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- shopping_items
ALTER TABLE shopping_items ADD COLUMN IF NOT EXISTS note_en TEXT;
ALTER TABLE shopping_items ADD COLUMN IF NOT EXISTS sort_order INT NOT NULL DEFAULT 0;
ALTER TABLE shopping_items ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE shopping_items ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- reading_list
ALTER TABLE reading_list ADD COLUMN IF NOT EXISTS city_ids TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE reading_list ADD COLUMN IF NOT EXISTS synopsis_en TEXT;
ALTER TABLE reading_list ADD COLUMN IF NOT EXISTS sort_order INT NOT NULL DEFAULT 0;
ALTER TABLE reading_list ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE reading_list ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- hotels
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS chinese_name TEXT;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS stars INT NOT NULL DEFAULT 4;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS price_min_usd INT NOT NULL DEFAULT 0;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS has_english_staff BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS english_staff_note TEXT;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS language_tip TEXT;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS location_note TEXT;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS booking_platforms TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS sort_order INT NOT NULL DEFAULT 0;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- home_tips
ALTER TABLE home_tips ADD COLUMN IF NOT EXISTS link_attraction_id TEXT;
ALTER TABLE home_tips ADD COLUMN IF NOT EXISTS sort_order INT NOT NULL DEFAULT 0;
ALTER TABLE home_tips ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE home_tips ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
