-- Beijing city_guides seed (from YOLO/Resources/Static/city_guides.json)
-- Run after 040_city_guides.sql (uses legacy meta_* columns; 042 migrates to meta_items)

BEGIN;

INSERT INTO city_guides (
  id, city_id, title_en, title_zh, subtitle, icon, badge,
  cover_images, body, audio_url, audio_title, audio_duration_seconds,
  audio_quote, audio_transcript, meta_duration, meta_distance, meta_stops,
  display_order, is_published
) VALUES (
  'beijing_highlights',
  'beijing',
  'Beijing Highlights',
  '北京精华',
  '8 must-see places, linked to each guide',
  '✦',
  NULL,
  ARRAY[]::TEXT[],
  '<p>From the Forbidden City to the Great Wall — eight essential stops that define imperial Beijing.</p>',
  NULL,
  NULL,
  0,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  0,
  TRUE
) ON CONFLICT (id) DO UPDATE SET
  city_id = EXCLUDED.city_id,
  title_en = EXCLUDED.title_en,
  title_zh = EXCLUDED.title_zh,
  subtitle = EXCLUDED.subtitle,
  icon = EXCLUDED.icon,
  badge = EXCLUDED.badge,
  cover_images = EXCLUDED.cover_images,
  body = EXCLUDED.body,
  audio_url = EXCLUDED.audio_url,
  audio_title = EXCLUDED.audio_title,
  audio_duration_seconds = EXCLUDED.audio_duration_seconds,
  audio_quote = EXCLUDED.audio_quote,
  audio_transcript = EXCLUDED.audio_transcript,
  meta_duration = EXCLUDED.meta_duration,
  meta_distance = EXCLUDED.meta_distance,
  meta_stops = EXCLUDED.meta_stops,
  display_order = EXCLUDED.display_order,
  is_published = EXCLUDED.is_published,
  updated_at = NOW();

INSERT INTO city_guides (
  id, city_id, title_en, title_zh, subtitle, icon, badge,
  cover_images, body, audio_url, audio_title, audio_duration_seconds,
  audio_quote, audio_transcript, meta_duration, meta_distance, meta_stops,
  display_order, is_published
) VALUES (
  'beijing_best_season',
  'beijing',
  'Best Season to Visit',
  '最佳季节',
  'Sep–Oct & Apr–May',
  '☀',
  NULL,
  ARRAY[]::TEXT[],
  '<p>Spring and autumn offer clear skies, mild temperatures, and golden foliage in the hutongs.</p>',
  NULL,
  NULL,
  0,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  1,
  TRUE
) ON CONFLICT (id) DO UPDATE SET
  city_id = EXCLUDED.city_id,
  title_en = EXCLUDED.title_en,
  title_zh = EXCLUDED.title_zh,
  subtitle = EXCLUDED.subtitle,
  icon = EXCLUDED.icon,
  badge = EXCLUDED.badge,
  cover_images = EXCLUDED.cover_images,
  body = EXCLUDED.body,
  audio_url = EXCLUDED.audio_url,
  audio_title = EXCLUDED.audio_title,
  audio_duration_seconds = EXCLUDED.audio_duration_seconds,
  audio_quote = EXCLUDED.audio_quote,
  audio_transcript = EXCLUDED.audio_transcript,
  meta_duration = EXCLUDED.meta_duration,
  meta_distance = EXCLUDED.meta_distance,
  meta_stops = EXCLUDED.meta_stops,
  display_order = EXCLUDED.display_order,
  is_published = EXCLUDED.is_published,
  updated_at = NOW();

INSERT INTO city_guides (
  id, city_id, title_en, title_zh, subtitle, icon, badge,
  cover_images, body, audio_url, audio_title, audio_duration_seconds,
  audio_quote, audio_transcript, meta_duration, meta_distance, meta_stops,
  display_order, is_published
) VALUES (
  'beijing_hutong_citywalk',
  'beijing',
  'Hutong Citywalk',
  '胡同漫步',
  '3.2 km · ~90 min · 5 stops',
  '🚶',
  'Citywalk',
  ARRAY[]::TEXT[],
  '<p>Beijing''s soul lives in its hutong — grey-brick lanes that have laced the old city since the Yuan dynasty.</p><h2>The Route</h2><p>Start at Lama Temple, thread Nanluoguxiang and Yandai Xiejie, then finish at the Bell &amp; Drum Towers.</p>',
  NULL,
  NULL,
  0,
  NULL,
  NULL,
  '~90 min',
  '3.2 km',
  5,
  2,
  TRUE
) ON CONFLICT (id) DO UPDATE SET
  city_id = EXCLUDED.city_id,
  title_en = EXCLUDED.title_en,
  title_zh = EXCLUDED.title_zh,
  subtitle = EXCLUDED.subtitle,
  icon = EXCLUDED.icon,
  badge = EXCLUDED.badge,
  cover_images = EXCLUDED.cover_images,
  body = EXCLUDED.body,
  audio_url = EXCLUDED.audio_url,
  audio_title = EXCLUDED.audio_title,
  audio_duration_seconds = EXCLUDED.audio_duration_seconds,
  audio_quote = EXCLUDED.audio_quote,
  audio_transcript = EXCLUDED.audio_transcript,
  meta_duration = EXCLUDED.meta_duration,
  meta_distance = EXCLUDED.meta_distance,
  meta_stops = EXCLUDED.meta_stops,
  display_order = EXCLUDED.display_order,
  is_published = EXCLUDED.is_published,
  updated_at = NOW();

COMMIT;
