-- 把签证引擎里实际有 grant 的国籍补进 passport_countries（grant 国家下拉的数据源）。
-- 由 visa.db 生成；ON CONFLICT DO NOTHING 只补缺，不覆盖已有人工维护的行。
INSERT INTO passport_countries (code, name, flag, is_active) VALUES
  ('AL', 'Albania', '🇦🇱', TRUE),
  ('AD', 'Andorra', '🇦🇩', TRUE),
  ('AG', 'Antigua and Barbuda', '🇦🇬', TRUE),
  ('AR', 'Argentina', '🇦🇷', TRUE),
  ('AM', 'Armenia', '🇦🇲', TRUE),
  ('AU', 'Australia', '🇦🇺', TRUE),
  ('AT', 'Austria', '🇦🇹', TRUE),
  ('AZ', 'Azerbaijan', '🇦🇿', TRUE),
  ('BS', 'Bahamas', '🇧🇸', TRUE),
  ('BH', 'Bahrain', '🇧🇭', TRUE),
  ('BB', 'Barbados', '🇧🇧', TRUE),
  ('BY', 'Belarus', '🇧🇾', TRUE),
  ('BE', 'Belgium', '🇧🇪', TRUE),
  ('BA', 'Bosnia and Herzegovina', '🇧🇦', TRUE),
  ('BR', 'Brazil', '🇧🇷', TRUE),
  ('BN', 'Brunei Darussalam', '🇧🇳', TRUE),
  ('BG', 'Bulgaria', '🇧🇬', TRUE),
  ('KH', 'Cambodia', '🇰🇭', TRUE),
  ('CA', 'Canada', '🇨🇦', TRUE),
  ('CL', 'Chile', '🇨🇱', TRUE),
  ('HR', 'Croatia', '🇭🇷', TRUE),
  ('CY', 'Cyprus', '🇨🇾', TRUE),
  ('CZ', 'Czechia', '🇨🇿', TRUE),
  ('DK', 'Denmark', '🇩🇰', TRUE),
  ('DM', 'Dominica', '🇩🇲', TRUE),
  ('EC', 'Ecuador', '🇪🇨', TRUE),
  ('EE', 'Estonia', '🇪🇪', TRUE),
  ('FJ', 'Fiji', '🇫🇯', TRUE),
  ('FI', 'Finland', '🇫🇮', TRUE),
  ('FR', 'France', '🇫🇷', TRUE),
  ('GE', 'Georgia', '🇬🇪', TRUE),
  ('DE', 'Germany', '🇩🇪', TRUE),
  ('GR', 'Greece', '🇬🇷', TRUE),
  ('GD', 'Grenada', '🇬🇩', TRUE),
  ('HU', 'Hungary', '🇭🇺', TRUE),
  ('IS', 'Iceland', '🇮🇸', TRUE),
  ('ID', 'Indonesia', '🇮🇩', TRUE),
  ('IE', 'Ireland', '🇮🇪', TRUE),
  ('IT', 'Italy', '🇮🇹', TRUE),
  ('JP', 'Japan', '🇯🇵', TRUE),
  ('KZ', 'Kazakhstan', '🇰🇿', TRUE),
  ('KR', 'Korea (Republic of)', '🇰🇷', TRUE),
  ('KW', 'Kuwait', '🇰🇼', TRUE),
  ('LA', 'Lao People''s Democratic Republic', '🇱🇦', TRUE),
  ('LV', 'Latvia', '🇱🇻', TRUE),
  ('LI', 'Liechtenstein', '🇱🇮', TRUE),
  ('LT', 'Lithuania', '🇱🇹', TRUE),
  ('LU', 'Luxembourg', '🇱🇺', TRUE),
  ('MY', 'Malaysia', '🇲🇾', TRUE),
  ('MV', 'Maldives', '🇲🇻', TRUE),
  ('MT', 'Malta', '🇲🇹', TRUE),
  ('MU', 'Mauritius', '🇲🇺', TRUE),
  ('MX', 'Mexico', '🇲🇽', TRUE),
  ('MC', 'Monaco', '🇲🇨', TRUE),
  ('ME', 'Montenegro', '🇲🇪', TRUE),
  ('MM', 'Myanmar', '🇲🇲', TRUE),
  ('NL', 'Netherlands', '🇳🇱', TRUE),
  ('NZ', 'New Zealand', '🇳🇿', TRUE),
  ('MK', 'North Macedonia', '🇲🇰', TRUE),
  ('NO', 'Norway', '🇳🇴', TRUE),
  ('OM', 'Oman', '🇴🇲', TRUE),
  ('PE', 'Peru', '🇵🇪', TRUE),
  ('PH', 'Philippines', '🇵🇭', TRUE),
  ('PL', 'Poland', '🇵🇱', TRUE),
  ('PT', 'Portugal', '🇵🇹', TRUE),
  ('QA', 'Qatar', '🇶🇦', TRUE),
  ('RO', 'Romania', '🇷🇴', TRUE),
  ('RU', 'Russian Federation', '🇷🇺', TRUE),
  ('WS', 'Samoa', '🇼🇸', TRUE),
  ('SM', 'San Marino', '🇸🇲', TRUE),
  ('SA', 'Saudi Arabia', '🇸🇦', TRUE),
  ('RS', 'Serbia', '🇷🇸', TRUE),
  ('SC', 'Seychelles', '🇸🇨', TRUE),
  ('SG', 'Singapore', '🇸🇬', TRUE),
  ('SK', 'Slovakia', '🇸🇰', TRUE),
  ('SI', 'Slovenia', '🇸🇮', TRUE),
  ('SB', 'Solomon Islands', '🇸🇧', TRUE),
  ('ES', 'Spain', '🇪🇸', TRUE),
  ('SR', 'Suriname', '🇸🇷', TRUE),
  ('SE', 'Sweden', '🇸🇪', TRUE),
  ('CH', 'Switzerland', '🇨🇭', TRUE),
  ('TH', 'Thailand', '🇹🇭', TRUE),
  ('TO', 'Tonga', '🇹🇴', TRUE),
  ('UA', 'Ukraine', '🇺🇦', TRUE),
  ('AE', 'United Arab Emirates', '🇦🇪', TRUE),
  ('GB', 'United Kingdom', '🇬🇧', TRUE),
  ('US', 'United States of America', '🇺🇸', TRUE),
  ('UY', 'Uruguay', '🇺🇾', TRUE),
  ('UZ', 'Uzbekistan', '🇺🇿', TRUE),
  ('VN', 'Viet Nam', '🇻🇳', TRUE)
ON CONFLICT (code) DO NOTHING;
