-- 080 · visa_countries：ISO 3166-1 全量 249 国受控词表（来自交付包 review.db）
-- grant 国家选择引此表；与 passport_countries(90) 分离：护照国籍展示 ≠ 签证词表。

CREATE TABLE IF NOT EXISTS visa_countries (
  country_code TEXT PRIMARY KEY,                 -- ISO 3166-1 alpha-2
  name_zh      TEXT NOT NULL DEFAULT '',
  name_en      TEXT NOT NULL DEFAULT '',
  flag_emoji   TEXT,
  is_territory BOOLEAN NOT NULL DEFAULT FALSE,    -- 1=非主权关境/属地（港澳台等），供 240h 第三地逻辑
  is_active    BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE visa_countries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read visa_countries" ON visa_countries;
CREATE POLICY "Public read visa_countries" ON visa_countries
  FOR SELECT USING (is_active = TRUE OR public.is_admin());
DROP POLICY IF EXISTS "Admin insert visa_countries" ON visa_countries;
CREATE POLICY "Admin insert visa_countries" ON visa_countries
  FOR INSERT TO authenticated WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS "Admin update visa_countries" ON visa_countries;
CREATE POLICY "Admin update visa_countries" ON visa_countries
  FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS "Admin delete visa_countries" ON visa_countries;
CREATE POLICY "Admin delete visa_countries" ON visa_countries
  FOR DELETE TO authenticated USING (public.is_admin());

INSERT INTO visa_countries (country_code, name_zh, name_en, flag_emoji, is_territory) VALUES
  ('AD', '安道尔', 'Andorra', '🇦🇩', FALSE),
  ('AE', '阿拉伯联合酋长国', 'United Arab Emirates', '🇦🇪', FALSE),
  ('AF', '阿富汗', 'Afghanistan', '🇦🇫', FALSE),
  ('AG', '安提瓜和巴布达', 'Antigua and Barbuda', '🇦🇬', FALSE),
  ('AI', '安圭拉', 'Anguilla', NULL, TRUE),
  ('AL', '阿尔巴尼亚', 'Albania', '🇦🇱', FALSE),
  ('AM', '亚美尼亚', 'Armenia', '🇦🇲', FALSE),
  ('AO', '安哥拉', 'Angola', '🇦🇴', FALSE),
  ('AQ', '南极洲', 'Antarctica', NULL, TRUE),
  ('AR', '阿根廷', 'Argentina', '🇦🇷', FALSE),
  ('AS', '美属萨摩亚', 'American Samoa', NULL, TRUE),
  ('AT', '奥地利', 'Austria', '🇦🇹', FALSE),
  ('AU', '澳大利亚', 'Australia', '🇦🇺', FALSE),
  ('AW', '阿鲁巴', 'Aruba', NULL, TRUE),
  ('AX', '奥兰群岛', 'Åland Islands', NULL, TRUE),
  ('AZ', '阿塞拜疆', 'Azerbaijan', '🇦🇿', FALSE),
  ('BA', '波斯尼亚和黑塞哥维那', 'Bosnia and Herzegovina', '🇧🇦', FALSE),
  ('BB', '巴巴多斯', 'Barbados', '🇧🇧', FALSE),
  ('BD', '孟加拉国', 'Bangladesh', '🇧🇩', FALSE),
  ('BE', '比利时', 'Belgium', '🇧🇪', FALSE),
  ('BF', '布基纳法索', 'Burkina Faso', '🇧🇫', FALSE),
  ('BG', '保加利亚', 'Bulgaria', '🇧🇬', FALSE),
  ('BH', '巴林', 'Bahrain', '🇧🇭', FALSE),
  ('BI', '布隆迪', 'Burundi', '🇧🇮', FALSE),
  ('BJ', '贝宁', 'Benin', '🇧🇯', FALSE),
  ('BL', '圣巴泰勒米', 'Saint Barthélemy', NULL, TRUE),
  ('BM', '百慕大', 'Bermuda', NULL, TRUE),
  ('BN', '文莱', 'Brunei Darussalam', '🇧🇳', FALSE),
  ('BO', '玻利维亚', 'Bolivia', '🇧🇴', FALSE),
  ('BQ', '博奈尔、圣尤斯特歇斯和萨巴', 'Bonaire, Sint Eustatius and Saba', NULL, TRUE),
  ('BR', '巴西', 'Brazil', '🇧🇷', FALSE),
  ('BS', '巴哈马', 'Bahamas', '🇧🇸', FALSE),
  ('BT', '不丹', 'Bhutan', '🇧🇹', FALSE),
  ('BV', '布维岛', 'Bouvet Island', NULL, TRUE),
  ('BW', '博茨瓦纳', 'Botswana', '🇧🇼', FALSE),
  ('BY', '白俄罗斯', 'Belarus', '🇧🇾', FALSE),
  ('BZ', '伯利兹', 'Belize', '🇧🇿', FALSE),
  ('CA', '加拿大', 'Canada', '🇨🇦', FALSE),
  ('CC', '科科斯（基林）群岛', 'Cocos (Keeling) Islands', NULL, TRUE),
  ('CD', '刚果（金）', 'Congo (Democratic Republic)', '🇨🇩', FALSE),
  ('CF', '中非共和国', 'Central African Republic', '🇨🇫', FALSE),
  ('CG', '刚果（布）', 'Congo', '🇨🇬', FALSE),
  ('CH', '瑞士', 'Switzerland', '🇨🇭', FALSE),
  ('CI', '科特迪瓦', 'Côte d''Ivoire', '🇨🇮', FALSE),
  ('CK', '库克群岛', 'Cook Islands', NULL, TRUE),
  ('CL', '智利', 'Chile', '🇨🇱', FALSE),
  ('CM', '喀麦隆', 'Cameroon', '🇨🇲', FALSE),
  ('CN', '中国', 'China', '🇨🇳', FALSE),
  ('CO', '哥伦比亚', 'Colombia', '🇨🇴', FALSE),
  ('CR', '哥斯达黎加', 'Costa Rica', '🇨🇷', FALSE),
  ('CU', '古巴', 'Cuba', '🇨🇺', FALSE),
  ('CV', '佛得角', 'Cabo Verde', '🇨🇻', FALSE),
  ('CW', '库拉索', 'Curaçao', NULL, TRUE),
  ('CX', '圣诞岛', 'Christmas Island', NULL, TRUE),
  ('CY', '塞浦路斯', 'Cyprus', '🇨🇾', FALSE),
  ('CZ', '捷克', 'Czechia', '🇨🇿', FALSE),
  ('DE', '德国', 'Germany', '🇩🇪', FALSE),
  ('DJ', '吉布提', 'Djibouti', '🇩🇯', FALSE),
  ('DK', '丹麦', 'Denmark', '🇩🇰', FALSE),
  ('DM', '多米尼克', 'Dominica', '🇩🇲', FALSE),
  ('DO', '多米尼加共和国', 'Dominican Republic', '🇩🇴', FALSE),
  ('DZ', '阿尔及利亚', 'Algeria', '🇩🇿', FALSE),
  ('EC', '厄瓜多尔', 'Ecuador', '🇪🇨', FALSE),
  ('EE', '爱沙尼亚', 'Estonia', '🇪🇪', FALSE),
  ('EG', '埃及', 'Egypt', '🇪🇬', FALSE),
  ('EH', '西撒哈拉', 'Western Sahara', NULL, TRUE),
  ('ER', '厄立特里亚', 'Eritrea', '🇪🇷', FALSE),
  ('ES', '西班牙', 'Spain', '🇪🇸', FALSE),
  ('ET', '埃塞俄比亚', 'Ethiopia', '🇪🇹', FALSE),
  ('FI', '芬兰', 'Finland', '🇫🇮', FALSE),
  ('FJ', '斐济', 'Fiji', '🇫🇯', FALSE),
  ('FK', '福克兰群岛（马尔维纳斯）', 'Falkland Islands (Malvinas)', NULL, TRUE),
  ('FM', '密克罗尼西亚联邦', 'Micronesia (Federated States)', '🇫🇲', FALSE),
  ('FO', '法罗群岛', 'Faroe Islands', NULL, TRUE),
  ('FR', '法国', 'France', '🇫🇷', FALSE),
  ('GA', '加蓬', 'Gabon', '🇬🇦', FALSE),
  ('GB', '英国', 'United Kingdom', '🇬🇧', FALSE),
  ('GD', '格林纳达', 'Grenada', '🇬🇩', FALSE),
  ('GE', '格鲁吉亚', 'Georgia', '🇬🇪', FALSE),
  ('GF', '法属圭亚那', 'French Guiana', NULL, TRUE),
  ('GG', '根西', 'Guernsey', NULL, TRUE),
  ('GH', '加纳', 'Ghana', '🇬🇭', FALSE),
  ('GI', '直布罗陀', 'Gibraltar', NULL, TRUE),
  ('GL', '格陵兰', 'Greenland', NULL, TRUE),
  ('GM', '冈比亚', 'Gambia', '🇬🇲', FALSE),
  ('GN', '几内亚', 'Guinea', '🇬🇳', FALSE),
  ('GP', '瓜德罗普', 'Guadeloupe', NULL, TRUE),
  ('GQ', '赤道几内亚', 'Equatorial Guinea', '🇬🇶', FALSE),
  ('GR', '希腊', 'Greece', '🇬🇷', FALSE),
  ('GS', '南乔治亚和南桑威奇群岛', 'South Georgia and the South Sandwich Islands', NULL, TRUE),
  ('GT', '危地马拉', 'Guatemala', '🇬🇹', FALSE),
  ('GU', '关岛', 'Guam', NULL, TRUE),
  ('GW', '几内亚比绍', 'Guinea-Bissau', '🇬🇼', FALSE),
  ('GY', '圭亚那', 'Guyana', '🇬🇾', FALSE),
  ('HK', '中国香港', 'Hong Kong', NULL, TRUE),
  ('HM', '赫德岛和麦克唐纳岛', 'Heard Island and McDonald Islands', NULL, TRUE),
  ('HN', '洪都拉斯', 'Honduras', '🇭🇳', FALSE),
  ('HR', '克罗地亚', 'Croatia', '🇭🇷', FALSE),
  ('HT', '海地', 'Haiti', '🇭🇹', FALSE),
  ('HU', '匈牙利', 'Hungary', '🇭🇺', FALSE),
  ('ID', '印度尼西亚', 'Indonesia', '🇮🇩', FALSE),
  ('IE', '爱尔兰', 'Ireland', '🇮🇪', FALSE),
  ('IL', '以色列', 'Israel', '🇮🇱', FALSE),
  ('IM', '马恩岛', 'Isle of Man', NULL, TRUE),
  ('IN', '印度', 'India', '🇮🇳', FALSE),
  ('IO', '英属印度洋领地', 'British Indian Ocean Territory', NULL, TRUE),
  ('IQ', '伊拉克', 'Iraq', '🇮🇶', FALSE),
  ('IR', '伊朗', 'Iran', '🇮🇷', FALSE),
  ('IS', '冰岛', 'Iceland', '🇮🇸', FALSE),
  ('IT', '意大利', 'Italy', '🇮🇹', FALSE),
  ('JE', '泽西', 'Jersey', NULL, TRUE),
  ('JM', '牙买加', 'Jamaica', '🇯🇲', FALSE),
  ('JO', '约旦', 'Jordan', '🇯🇴', FALSE),
  ('JP', '日本', 'Japan', '🇯🇵', FALSE),
  ('KE', '肯尼亚', 'Kenya', '🇰🇪', FALSE),
  ('KG', '吉尔吉斯斯坦', 'Kyrgyzstan', '🇰🇬', FALSE),
  ('KH', '柬埔寨', 'Cambodia', '🇰🇭', FALSE),
  ('KI', '基里巴斯', 'Kiribati', '🇰🇮', FALSE),
  ('KM', '科摩罗', 'Comoros', '🇰🇲', FALSE),
  ('KN', '圣基茨和尼维斯', 'Saint Kitts and Nevis', '🇰🇳', FALSE),
  ('KP', '朝鲜', 'Korea (Democratic People''s Republic)', '🇰🇵', FALSE),
  ('KR', '韩国', 'Korea (Republic of)', '🇰🇷', FALSE),
  ('KW', '科威特', 'Kuwait', '🇰🇼', FALSE),
  ('KY', '开曼群岛', 'Cayman Islands', NULL, TRUE),
  ('KZ', '哈萨克斯坦', 'Kazakhstan', '🇰🇿', FALSE),
  ('LA', '老挝', 'Lao People''s Democratic Republic', '🇱🇦', FALSE),
  ('LB', '黎巴嫩', 'Lebanon', '🇱🇧', FALSE),
  ('LC', '圣卢西亚', 'Saint Lucia', '🇱🇨', FALSE),
  ('LI', '列支敦士登', 'Liechtenstein', '🇱🇮', FALSE),
  ('LK', '斯里兰卡', 'Sri Lanka', '🇱🇰', FALSE),
  ('LR', '利比里亚', 'Liberia', '🇱🇷', FALSE),
  ('LS', '莱索托', 'Lesotho', '🇱🇸', FALSE),
  ('LT', '立陶宛', 'Lithuania', '🇱🇹', FALSE),
  ('LU', '卢森堡', 'Luxembourg', '🇱🇺', FALSE),
  ('LV', '拉脱维亚', 'Latvia', '🇱🇻', FALSE),
  ('LY', '利比亚', 'Libya', '🇱🇾', FALSE),
  ('MA', '摩洛哥', 'Morocco', '🇲🇦', FALSE),
  ('MC', '摩纳哥', 'Monaco', '🇲🇨', FALSE),
  ('MD', '摩尔多瓦', 'Moldova', '🇲🇩', FALSE),
  ('ME', '黑山', 'Montenegro', '🇲🇪', FALSE),
  ('MF', '圣马丁（法属）', 'Saint Martin (French part)', NULL, TRUE),
  ('MG', '马达加斯加', 'Madagascar', '🇲🇬', FALSE),
  ('MH', '马绍尔群岛', 'Marshall Islands', '🇲🇭', FALSE),
  ('MK', '北马其顿', 'North Macedonia', '🇲🇰', FALSE),
  ('ML', '马里', 'Mali', '🇲🇱', FALSE),
  ('MM', '缅甸', 'Myanmar', '🇲🇲', FALSE),
  ('MN', '蒙古', 'Mongolia', '🇲🇳', FALSE),
  ('MO', '中国澳门', 'Macao', NULL, TRUE),
  ('MP', '北马里亚纳群岛', 'Northern Mariana Islands', NULL, TRUE),
  ('MQ', '马提尼克', 'Martinique', NULL, TRUE),
  ('MR', '毛里塔尼亚', 'Mauritania', '🇲🇷', FALSE),
  ('MS', '蒙特塞拉特', 'Montserrat', NULL, TRUE),
  ('MT', '马耳他', 'Malta', '🇲🇹', FALSE),
  ('MU', '毛里求斯', 'Mauritius', '🇲🇺', FALSE),
  ('MV', '马尔代夫', 'Maldives', '🇲🇻', FALSE),
  ('MW', '马拉维', 'Malawi', '🇲🇼', FALSE),
  ('MX', '墨西哥', 'Mexico', '🇲🇽', FALSE),
  ('MY', '马来西亚', 'Malaysia', '🇲🇾', FALSE),
  ('MZ', '莫桑比克', 'Mozambique', '🇲🇿', FALSE),
  ('NA', '纳米比亚', 'Namibia', '🇳🇦', FALSE),
  ('NC', '新喀里多尼亚', 'New Caledonia', NULL, TRUE),
  ('NE', '尼日尔', 'Niger', '🇳🇪', FALSE),
  ('NF', '诺福克岛', 'Norfolk Island', NULL, TRUE),
  ('NG', '尼日利亚', 'Nigeria', '🇳🇬', FALSE),
  ('NI', '尼加拉瓜', 'Nicaragua', '🇳🇮', FALSE),
  ('NL', '荷兰', 'Netherlands', '🇳🇱', FALSE),
  ('NO', '挪威', 'Norway', '🇳🇴', FALSE),
  ('NP', '尼泊尔', 'Nepal', '🇳🇵', FALSE),
  ('NR', '瑙鲁', 'Nauru', '🇳🇷', FALSE),
  ('NU', '纽埃', 'Niue', NULL, TRUE),
  ('NZ', '新西兰', 'New Zealand', '🇳🇿', FALSE),
  ('OM', '阿曼', 'Oman', '🇴🇲', FALSE),
  ('PA', '巴拿马', 'Panama', '🇵🇦', FALSE),
  ('PE', '秘鲁', 'Peru', '🇵🇪', FALSE),
  ('PF', '法属波利尼西亚', 'French Polynesia', NULL, TRUE),
  ('PG', '巴布亚新几内亚', 'Papua New Guinea', '🇵🇬', FALSE),
  ('PH', '菲律宾', 'Philippines', '🇵🇭', FALSE),
  ('PK', '巴基斯坦', 'Pakistan', '🇵🇰', FALSE),
  ('PL', '波兰', 'Poland', '🇵🇱', FALSE),
  ('PM', '圣皮埃尔和密克隆', 'Saint Pierre and Miquelon', NULL, TRUE),
  ('PN', '皮特凯恩', 'Pitcairn', NULL, TRUE),
  ('PR', '波多黎各', 'Puerto Rico', NULL, TRUE),
  ('PS', '巴勒斯坦', 'Palestine, State of', '🇵🇸', FALSE),
  ('PT', '葡萄牙', 'Portugal', '🇵🇹', FALSE),
  ('PW', '帕劳', 'Palau', '🇵🇼', FALSE),
  ('PY', '巴拉圭', 'Paraguay', '🇵🇾', FALSE),
  ('QA', '卡塔尔', 'Qatar', '🇶🇦', FALSE),
  ('RE', '留尼汪', 'Réunion', NULL, TRUE),
  ('RO', '罗马尼亚', 'Romania', '🇷🇴', FALSE),
  ('RS', '塞尔维亚', 'Serbia', '🇷🇸', FALSE),
  ('RU', '俄罗斯', 'Russian Federation', '🇷🇺', FALSE),
  ('RW', '卢旺达', 'Rwanda', '🇷🇼', FALSE),
  ('SA', '沙特阿拉伯', 'Saudi Arabia', '🇸🇦', FALSE),
  ('SB', '所罗门群岛', 'Solomon Islands', '🇸🇧', FALSE),
  ('SC', '塞舌尔', 'Seychelles', '🇸🇨', FALSE),
  ('SD', '苏丹', 'Sudan', '🇸🇩', FALSE),
  ('SE', '瑞典', 'Sweden', '🇸🇪', FALSE),
  ('SG', '新加坡', 'Singapore', '🇸🇬', FALSE),
  ('SH', '圣赫勒拿、阿森松和特里斯坦-达库尼亚', 'Saint Helena, Ascension and Tristan da Cunha', NULL, TRUE),
  ('SI', '斯洛文尼亚', 'Slovenia', '🇸🇮', FALSE),
  ('SJ', '斯瓦尔巴和扬马延', 'Svalbard and Jan Mayen', NULL, TRUE),
  ('SK', '斯洛伐克', 'Slovakia', '🇸🇰', FALSE),
  ('SL', '塞拉利昂', 'Sierra Leone', '🇸🇱', FALSE),
  ('SM', '圣马力诺', 'San Marino', '🇸🇲', FALSE),
  ('SN', '塞内加尔', 'Senegal', '🇸🇳', FALSE),
  ('SO', '索马里', 'Somalia', '🇸🇴', FALSE),
  ('SR', '苏里南', 'Suriname', '🇸🇷', FALSE),
  ('SS', '南苏丹', 'South Sudan', '🇸🇸', FALSE),
  ('ST', '圣多美和普林西比', 'Sao Tome and Principe', '🇸🇹', FALSE),
  ('SV', '萨尔瓦多', 'El Salvador', '🇸🇻', FALSE),
  ('SX', '圣马丁（荷属）', 'Sint Maarten (Dutch part)', NULL, TRUE),
  ('SY', '叙利亚', 'Syrian Arab Republic', '🇸🇾', FALSE),
  ('SZ', '斯威士兰', 'Eswatini', '🇸🇿', FALSE),
  ('TC', '特克斯和凯科斯群岛', 'Turks and Caicos Islands', NULL, TRUE),
  ('TD', '乍得', 'Chad', '🇹🇩', FALSE),
  ('TF', '法属南方领地', 'French Southern Territories', NULL, TRUE),
  ('TG', '多哥', 'Togo', '🇹🇬', FALSE),
  ('TH', '泰国', 'Thailand', '🇹🇭', FALSE),
  ('TJ', '塔吉克斯坦', 'Tajikistan', '🇹🇯', FALSE),
  ('TK', '托克劳', 'Tokelau', NULL, TRUE),
  ('TL', '东帝汶', 'Timor-Leste', '🇹🇱', FALSE),
  ('TM', '土库曼斯坦', 'Turkmenistan', '🇹🇲', FALSE),
  ('TN', '突尼斯', 'Tunisia', '🇹🇳', FALSE),
  ('TO', '汤加', 'Tonga', '🇹🇴', FALSE),
  ('TR', '土耳其', 'Türkiye', '🇹🇷', FALSE),
  ('TT', '特立尼达和多巴哥', 'Trinidad and Tobago', '🇹🇹', FALSE),
  ('TV', '图瓦卢', 'Tuvalu', '🇹🇻', FALSE),
  ('TW', '中国台湾', 'Taiwan (Province of China)', NULL, TRUE),
  ('TZ', '坦桑尼亚', 'Tanzania', '🇹🇿', FALSE),
  ('UA', '乌克兰', 'Ukraine', '🇺🇦', FALSE),
  ('UG', '乌干达', 'Uganda', '🇺🇬', FALSE),
  ('UM', '美国本土外小岛屿', 'United States Minor Outlying Islands', NULL, TRUE),
  ('US', '美国', 'United States of America', '🇺🇸', FALSE),
  ('UY', '乌拉圭', 'Uruguay', '🇺🇾', FALSE),
  ('UZ', '乌兹别克斯坦', 'Uzbekistan', '🇺🇿', FALSE),
  ('VA', '梵蒂冈', 'Holy See', '🇻🇦', FALSE),
  ('VC', '圣文森特和格林纳丁斯', 'Saint Vincent and the Grenadines', '🇻🇨', FALSE),
  ('VE', '委内瑞拉', 'Venezuela', '🇻🇪', FALSE),
  ('VG', '英属维尔京群岛', 'Virgin Islands (British)', NULL, TRUE),
  ('VI', '美属维尔京群岛', 'Virgin Islands (U.S.)', NULL, TRUE),
  ('VN', '越南', 'Viet Nam', '🇻🇳', FALSE),
  ('VU', '瓦努阿图', 'Vanuatu', '🇻🇺', FALSE),
  ('WF', '瓦利斯和富图纳', 'Wallis and Futuna', NULL, TRUE),
  ('WS', '萨摩亚', 'Samoa', '🇼🇸', FALSE),
  ('YE', '也门', 'Yemen', '🇾🇪', FALSE),
  ('YT', '马约特', 'Mayotte', NULL, TRUE),
  ('ZA', '南非', 'South Africa', '🇿🇦', FALSE),
  ('ZM', '赞比亚', 'Zambia', '🇿🇲', FALSE),
  ('ZW', '津巴布韦', 'Zimbabwe', '🇿🇼', FALSE)
ON CONFLICT (country_code) DO UPDATE SET
  name_zh = EXCLUDED.name_zh, name_en = EXCLUDED.name_en,
  flag_emoji = EXCLUDED.flag_emoji, is_territory = EXCLUDED.is_territory;
