-- 081 · 政策/grant 补齐交付包字段 + 从 review.db 回填值
-- 政策: entry_count(入境次数) / passport_ordinary_only(仅普通护照) / purpose(入境目的)
-- grant: entry_count_override / announced_date(公告日) / evidence_quote(原文引文)

ALTER TABLE visa_policies_v2 ADD COLUMN IF NOT EXISTS entry_count TEXT;
ALTER TABLE visa_policies_v2 ADD COLUMN IF NOT EXISTS passport_ordinary_only BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE visa_policies_v2 ADD COLUMN IF NOT EXISTS purpose JSONB;
ALTER TABLE visa_policy_grants_v2 ADD COLUMN IF NOT EXISTS entry_count_override TEXT;
ALTER TABLE visa_policy_grants_v2 ADD COLUMN IF NOT EXISTS announced_date TEXT;
ALTER TABLE visa_policy_grants_v2 ADD COLUMN IF NOT EXISTS evidence_quote TEXT;

-- 回填政策（8 条）
UPDATE visa_policies_v2 SET entry_count='multiple', passport_ordinary_only=TRUE, purpose='["tourism", "business", "family", "transit"]'::jsonb WHERE id='mutual_exempt';
UPDATE visa_policies_v2 SET entry_count='per_entry', passport_ordinary_only=TRUE, purpose='["tourism", "business", "family", "transit"]'::jsonb WHERE id='unilateral_30d';
UPDATE visa_policies_v2 SET entry_count='per_entry', passport_ordinary_only=FALSE, purpose='["tourism", "business", "family", "transit"]'::jsonb WHERE id='twov_240h';
UPDATE visa_policies_v2 SET entry_count='per_entry', passport_ordinary_only=FALSE, purpose='["transit"]'::jsonb WHERE id='twov_24h';
UPDATE visa_policies_v2 SET entry_count='per_entry', passport_ordinary_only=TRUE, purpose='["tourism", "business", "family", "medical", "exhibition", "sports"]'::jsonb WHERE id='hainan_30d';
UPDATE visa_policies_v2 SET entry_count='single', passport_ordinary_only=TRUE, purpose='["tourism"]'::jsonb WHERE id='group_asean_xsbn';
UPDATE visa_policies_v2 SET entry_count='single', passport_ordinary_only=FALSE, purpose='["tourism"]'::jsonb WHERE id='cruise_15d';
UPDATE visa_policies_v2 SET entry_count='single', passport_ordinary_only=TRUE, purpose='["tourism"]'::jsonb WHERE id='visa_L';

-- 回填 grant（201 verified，按 policy_id+country_code 匹配）
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='RU';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='GB';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='FR';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='DE';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='NO';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='UA';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='IT';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='AT';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='FI';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='NL';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='DK';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='CH';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='SE';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='ES';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='BE';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='CZ';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='EE';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='GR';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='HU';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='IS';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='LV';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='LT';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='LU';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='MT';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='PL';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='PT';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='SK';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='SI';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='IE';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='CY';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='BG';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='RO';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='RS';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='HR';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='BA';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='ME';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='MK';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='AL';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='US';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='CA';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='BR';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='MX';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='AR';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='CL';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='AU';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='NZ';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='KR';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='JP';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='SG';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='MY';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='TH';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='KZ';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='PH';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='ID';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='BN';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='AE';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='QA';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='MC';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局59国免签公告国别名单（按原文顺序列入本国）' WHERE policy_id='hainan_30d' AND upper(country_code)='BY';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='AT';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='BE';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='CZ';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='DK';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='EE';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='FI';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='FR';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='DE';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='GR';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='HU';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='IS';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='IT';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='LV';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='LT';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='LU';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='MT';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='NL';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='PL';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='PT';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='SK';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='SI';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='ES';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='SE';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='CH';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='MC';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='RU';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='GB';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='IE';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='CY';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='BG';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='RO';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='UA';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='RS';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='HR';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='BA';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='ME';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='MK';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='AL';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='BY';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='NO';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='US';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='CA';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='BR';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='MX';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='AR';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='CL';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='AU';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='NZ';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='KR';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='JP';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='SG';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='BN';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='AE';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='QA';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局240h过境免签公告国别名单(欧40/美6/洋2/亚7=55)' WHERE policy_id='twov_240h' AND upper(country_code)='ID';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='搜索摘要"中方对文莱持普通护照人员的免签政策未设施行期限";延长通知未单列文莱' WHERE policy_id='unilateral_30d' AND upper(country_code)='BN';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='搜索摘要"对俄罗斯持普通护照人员的免签政策施行至2027年12月31日"' WHERE policy_id='unilateral_30d' AND upper(country_code)='RU';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date='2025-11-03', evidence_quote='延长通知"中方将于2025年11月10日至2026年12月31日对瑞典免签"' WHERE policy_id='unilateral_30d' AND upper(country_code)='SE';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='FR';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='DE';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='IT';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='NL';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='ES';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='CH';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='IE';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='HU';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='AT';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='BE';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='LU';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='PL';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='SI';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='PT';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='GR';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='CY';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='SK';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='NO';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='FI';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='DK';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='IS';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='AD';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='MC';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='LI';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='BG';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='RO';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='HR';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='ME';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='MK';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='MT';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='EE';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='LV';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='GB';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='AU';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='NZ';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='KR';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='JP';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='SA';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='OM';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='KW';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='BH';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='BR';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='AR';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='CL';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='PE';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='UY';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='移民局名单"经商、旅游观光、探亲访友、交流访问、过境不超过30日";延长通知"延期至2026年12月31日24时"' WHERE policy_id='unilateral_30d' AND upper(country_code)='CA';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='阿尔巴尼亚:公务普通、普通护照 2023.03.18' WHERE policy_id='mutual_exempt' AND upper(country_code)='AL';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='阿联酋:普通护照 2018.01.16' WHERE policy_id='mutual_exempt' AND upper(country_code)='AE';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='阿塞拜疆:普通护照 2025.07.16' WHERE policy_id='mutual_exempt' AND upper(country_code)='AZ';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='安提瓜和巴布达:中方外交/公务/公务普通/普通护照 2024.05.11' WHERE policy_id='mutual_exempt' AND upper(country_code)='AG';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='巴巴多斯:普通护照 2017.06.01' WHERE policy_id='mutual_exempt' AND upper(country_code)='BB';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='巴哈马:中方外交/公务/公务普通/普通护照 2014.02.12' WHERE policy_id='mutual_exempt' AND upper(country_code)='BS';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='白俄罗斯:普通护照 2018.8.10' WHERE policy_id='mutual_exempt' AND upper(country_code)='BY';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='波黑:普通护照 2018.05.29' WHERE policy_id='mutual_exempt' AND upper(country_code)='BA';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='多米尼克:普通护照 2022.09.19' WHERE policy_id='mutual_exempt' AND upper(country_code)='DM';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='厄瓜多尔:普通护照 2016.08.18 ⚠️原文注"中方普通护照持有者赴厄瓜多尔暂需事先办理签证"——对等性存疑,厄方公民来华是否仍免待Song核' WHERE policy_id='mutual_exempt' AND upper(country_code)='EC';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='斐济:外交/公务/公务普通/普通护照 2015.03.14' WHERE policy_id='mutual_exempt' AND upper(country_code)='FJ';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='格林纳达:公务普通、普通护照 2015.06.10' WHERE policy_id='mutual_exempt' AND upper(country_code)='GD';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='格鲁吉亚:普通护照 2024.05.28' WHERE policy_id='mutual_exempt' AND upper(country_code)='GE';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='马尔代夫:中方外交/公务/公务普通/普通护照及旅行证 2022.05.20' WHERE policy_id='mutual_exempt' AND upper(country_code)='MV';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='马来西亚:中方公务普通/普通护照·马方普通护照 2025.07.17' WHERE policy_id='mutual_exempt' AND upper(country_code)='MY';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='毛里求斯:外交/公务/公务普通/普通护照 2013.10.31' WHERE policy_id='mutual_exempt' AND upper(country_code)='MU';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='萨摩亚:中方外交/公务/公务普通/普通护照 2025.04.02' WHERE policy_id='mutual_exempt' AND upper(country_code)='WS';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='塞尔维亚:普通护照 2017.01.15' WHERE policy_id='mutual_exempt' AND upper(country_code)='RS';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='塞舌尔:外交/公务/公务普通/普通护照 2013.06.26' WHERE policy_id='mutual_exempt' AND upper(country_code)='SC';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='圣马力诺:外交/公务/普通护照 1985.07.22' WHERE policy_id='mutual_exempt' AND upper(country_code)='SM';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='苏里南:外交/公务/公务普通/普通护照 2021.05.01' WHERE policy_id='mutual_exempt' AND upper(country_code)='SR';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='所罗门群岛:普通护照 2024.12.28' WHERE policy_id='mutual_exempt' AND upper(country_code)='SB';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='泰国:中方公务普通/普通护照·泰方普通护照 2024.03.01' WHERE policy_id='mutual_exempt' AND upper(country_code)='TH';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='汤加:普通护照 2016.08.19' WHERE policy_id='mutual_exempt' AND upper(country_code)='TO';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='乌兹别克斯坦:中方公务/公务普通/普通护照·乌方普通护照 2025.06.01' WHERE policy_id='mutual_exempt' AND upper(country_code)='UZ';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='新加坡:普通护照 2024.02.09' WHERE policy_id='mutual_exempt' AND upper(country_code)='SG';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='亚美尼亚:普通护照 2020.01.19' WHERE policy_id='mutual_exempt' AND upper(country_code)='AM';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='公告"马来西亚、印度尼西亚、泰国、菲律宾、新加坡、文莱、越南、老挝、缅甸、柬埔寨…旅游团(2人及以上)持普通护照…团进团出"' WHERE policy_id='group_asean_xsbn' AND upper(country_code)='MY';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='公告"马来西亚、印度尼西亚、泰国、菲律宾、新加坡、文莱、越南、老挝、缅甸、柬埔寨…旅游团(2人及以上)持普通护照…团进团出"' WHERE policy_id='group_asean_xsbn' AND upper(country_code)='ID';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='公告"马来西亚、印度尼西亚、泰国、菲律宾、新加坡、文莱、越南、老挝、缅甸、柬埔寨…旅游团(2人及以上)持普通护照…团进团出"' WHERE policy_id='group_asean_xsbn' AND upper(country_code)='TH';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='公告"马来西亚、印度尼西亚、泰国、菲律宾、新加坡、文莱、越南、老挝、缅甸、柬埔寨…旅游团(2人及以上)持普通护照…团进团出"' WHERE policy_id='group_asean_xsbn' AND upper(country_code)='PH';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='公告"马来西亚、印度尼西亚、泰国、菲律宾、新加坡、文莱、越南、老挝、缅甸、柬埔寨…旅游团(2人及以上)持普通护照…团进团出"' WHERE policy_id='group_asean_xsbn' AND upper(country_code)='SG';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='公告"马来西亚、印度尼西亚、泰国、菲律宾、新加坡、文莱、越南、老挝、缅甸、柬埔寨…旅游团(2人及以上)持普通护照…团进团出"' WHERE policy_id='group_asean_xsbn' AND upper(country_code)='BN';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='公告"马来西亚、印度尼西亚、泰国、菲律宾、新加坡、文莱、越南、老挝、缅甸、柬埔寨…旅游团(2人及以上)持普通护照…团进团出"' WHERE policy_id='group_asean_xsbn' AND upper(country_code)='VN';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='公告"马来西亚、印度尼西亚、泰国、菲律宾、新加坡、文莱、越南、老挝、缅甸、柬埔寨…旅游团(2人及以上)持普通护照…团进团出"' WHERE policy_id='group_asean_xsbn' AND upper(country_code)='LA';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='公告"马来西亚、印度尼西亚、泰国、菲律宾、新加坡、文莱、越南、老挝、缅甸、柬埔寨…旅游团(2人及以上)持普通护照…团进团出"' WHERE policy_id='group_asean_xsbn' AND upper(country_code)='MM';
UPDATE visa_policy_grants_v2 SET entry_count_override=NULL, announced_date=NULL, evidence_quote='公告"马来西亚、印度尼西亚、泰国、菲律宾、新加坡、文莱、越南、老挝、缅甸、柬埔寨…旅游团(2人及以上)持普通护照…团进团出"' WHERE policy_id='group_asean_xsbn' AND upper(country_code)='KH';
